### ISSUE TITLE
Banner 480x32 supported ?

### ISSUE THREAD

**Issue by linked67** [mopub/mopub-ios-sdk#100]
I have setup custom format 480x32 in mupob dashboard for my app and i'm wondering if i have something special to make it work ?

I only get this, even with setTesting to TRUE:
MOPUB: Banner ad view is fetching ad network type: clear
MOPUB: No ads found for ad unit: ba2d00ac205442e0a357822710a30a22
MOPUB: Banner view (ba2d00ac205442e0a357822710a30a22) failed. Error: Error Domain=com.mopub.iossdk Code=0 "The operation couldn’t be completed. (com.mopub.iossdk error 0.)"

I want to make it work with iad and admob. There is a special key to use mentionned in the admob wiki to use this format but i don't know if mupob support it.

**Comment by hoangthanhdoan** [comment]
Me too!
I got the mesage:

MOPUB: Banner ad view is fetching ad network type: clear
MoPubSampleApp[4476:44090] MOPUB: No ads found for ad unit: 10f9a9d4c1624f0fb374619a6db8296e
MoPubSampleApp[4476:44090] MOPUB: Banner view (10f9a9d4c1624f0fb374619a6db8296e) failed. Error: Error Domain=com.mopub.iossdk Code=0 "The operation couldn’t be completed. (com.mopub.iossdk error 0.)

**Comment by MrYogi** [comment]
i am getting same error for 320x50 native Banner ad unit:
MOPUB: Banner ad view is fetching ad network type: clear
MoPubSampleApp[4476:44090] MOPUB: No ads found for ad unit

 any idea for cause?

**Comment by linked67** [comment]
I have found that clear means there is no ads to show.

Since a few months, if you have too few ads request, your ads get out of the caching system of mopub.
This result in a very poor fill rate… except if you have enough request.

I have setup a fallback system to Admob in the case Mopub has no ads to show. This result i less request and the fill rate is going more down but at least i have always something to show.

You can see my helper code here:
https://github.com/linked67/mopub-helper
