### ISSUE TITLE
MRConstants.h

### ISSUE THREAD

**Issue by Alexandeer** [mopub/mopub-ios-sdk#102]
MRConstants.h:9:5: Redefinition of enumerator 'MRAdViewPlacementTypeInline'
MRConstants.h:10:5: Redefinition of enumerator 'MRAdViewPlacementTypeInterstitial'
MRConstants.h:15:5: Redefinition of enumerator 'MRAdViewStateHidden'
MRConstants.h:16:5: Redefinition of enumerator 'MRAdViewStateDefault'
MRConstants.h:17:5: Redefinition of enumerator 'MRAdViewStateExpanded'

**Comment by Kelcey** [comment]
Hello,

Sorry or the late response. Could you tell me which file has the definition already?

Thanks!
