### ISSUE TITLE
disableRequestHandling during interstitial appearance causes issues with ad creative.

### ISSUE THREAD

**Issue by netpro2k** [mopub/mopub-ios-sdk#104]
We have an MRAID interstitial ad creative that we are serving successfully to several MRAID ad containers (including mopub-android) but fails to correctly load on mopub-ios. The issue is that the ad creative attempts to load an iframe after the ad is considered both "ready" and "viewable" (using the relevant MRAID status methods and events). On mopub-ios there is a short period of time after the interstitial is shown that request loading is disabled due to:

https://github.com/mopub/mopub-ios-sdk/blob/master/MoPubSDK/Internal/MRAID/MPMRAIDInterstitialViewController.m#L51

it is during this period that the MRAID ready event fires, and `mraid.isViewable()` is true, and the ad creative attempts to create an iframe which fails to load. Adding a short delay (750ms or so) to the loading of the iframe does resolve this issue (as does commenting this line out of the SDK) but it is not an ideal solution as it is non-deterministic and adds unnecessary loading time to the ad.

Why is request loading halted during interstitial appearance, and is there some other event we should be listening for to know when it is again safe to load content?

**Comment by loisaidasam** [comment]
:+1:

**Comment by alicerp** [comment]
Hi! Are you still experiencing this with the latest SDK?

For additional questions, feel free to check out https://twittercommunity.com/c/fabric/mopub or email support@mopub.com.

**Comment by alicerp** [comment]
Hi there!

I'm following up with the MoPub team regarding your question.

Please note that the MoPub Github Issue Reporting Section will now be housed directly on the Twitter Developer Community Forum.

Please visit https://twittercommunity.com/c/fabric/mopub for any additional support questions or feel free to email suport@mopub.com.

Thank you for your patience and understanding.

Alice
