### ISSUE TITLE
Add support for Google AdMob iOS SDK 7.0

### ISSUE THREAD

**Issue by yood** [mopub/mopub-ios-sdk#112]
Please add support for the latest Google AdMob iOS SDK, version 7.0. From their release notes
(https://developers.google.com/mobile-ads-sdk/rel-notes#ios):

- Dropped support for iOS 5.
- Released SDK as a framework.
- Removed dependency on the -ObjC linker flag.
- Improved ad loading time on iOS 8.
- Added requestAgent property to GADRequest. Third-party integrations should set this property to denote the platform from which the request originated.
- Added new DFPRequest class, which supports roadblocks/competitive exclusions, custom targeting, and category exclusions.
- Moved publisherProvidedID property from DFPExtras to DFPRequest.
- Replaced GADAdMobExtras and DFPExtras with a single GADExtras class.
- Deprecated GADBannerView's hasAutoRefreshed property.
- Removed the GAD_SIMULATOR_ID macro—test ads are automatically enabled in the simulator when using GADBannerView and GADInterstitial.
- Removed GADRequest's mediationExtras, additionalParameters, and testing properties.
- Deprecated GADRequest's setBirthdayWithMonth:day:year:.
- Removed GADRequest's addKeyword: method.
- Removed DFPSwipeableBannerView class.

Thanks!

**Comment by Toinouze** [comment]
+1

**Comment by proth** [comment]
+1

**Comment by clementbarry** [comment]
+1

**Comment by burditto** [comment]
+1

**Comment by erysaj** [comment]
+1

**Comment by nikmin** [comment]
+1

**Comment by jowkame** [comment]
+1

**Comment by MoJRen** [comment]
hi all, admob 7.0 support will be shipped in our next release, thank you for your patience

**Comment by yood** [comment]
Great! Just noticed that the latest version is now 7.1. Could you support that if possible?

**Comment by victorfigol** [comment]
+1

**Comment by blogvinskiy** [comment]
We shipped support for 7.1 in Version 3.7 of our release. Thanks!
