### ISSUE TITLE
MRAID Interstitial MPVast XML parsing issue

### ISSUE THREAD

**Issue by evilbert103** [mopub/mopub-ios-sdk#117]
Hi there, I'm having trouble getting MRAID interstitials to work for iOS. I work in Adobe AIR and created my own MoPub ANE quite some time ago. MRAID interstitials have never loaded correctly in my project and I recently decided to look into why. Here is what I've discovered and I hope you might have a better solution than what I found to fix the problem.

Firstly, each time I get an MRAID interstitial from MoPub it fails and immediately tries to load 'mopub:failLoad'. Getting my hands into the javascript of the WebView it appears that the processing of the XML returned by MoPub is handled incorrectly. In the vast2html5.min.js javascript file loaded from the returned html blob, the function 'mpVast.parseXML' is throwing an exception on the '$.parseXML' call. Fiddling around a bit further it appears the function is unable to parse the XML because the urls listed inside of the XML (<Error>, <Impression>, etc) all end up with actual '&' symbols instead of the ascii encoded '&amp;' that are in the original html blob returned by MoPub. I can fix this issue by editing the 'mpUtils.cleanXML' function to add a '.replace(/&/g, "&amp;")' to the end of the return statement chain. This is quite ugly, but doing so in my hacked build results in the MRAID videos playing as expected. 

Now I'm no javascript+html expert but if I take the html blob returned from MoPub (which has '&amp;' characters in it as it presumably should) and I open that file in a browser, examining the html of the page shows that all of the '&amp;' instances are immediately turning into '&' characters. So I am not quite sure regarding the correct course of action.

Now obviously my quick fix is difficult to hack in so I am hoping that you might have some better ideas for how I can fix this problem. Additionally this is tricky to explain so I'm happy to elaborate on anything, or add in some actual code snip its if that would help, just let me know.

Thanks!

**Comment by alicerp** [comment]
Could you please provide the VAST response and full device logs to support@mopub.com?

For additional questions, feel free to check out https://twittercommunity.com/c/fabric/mopub or email support@mopub.com.
