### ISSUE TITLE
Presenting ads in a container view

### ISSUE THREAD

**Issue by TimOliver** [mopub/mopub-ios-sdk#118]
Hi there!

I'm developing an app that uses a 'magazine' style format to present content in a fullscreen, horizontally swiping scroll view. As such, it would be perfect for my design needs if I could simply embed full-screen ads as another 'page' in my scroll view.

From looking at the API, it looks like the only official way to display fullscreen ads is to have them pop up modally from another view controller.

Is there a way where I could present the ad content in a container view instead?

Thanks!

**Comment by RadiumOneDrew** [comment]
You need a full screen banner ad for that purpose.

Drew Colace | Development Manager / Architect - Mobile
e drew@radiumone.com <mailto:gchahal@radiumone.com>
