### ISSUE TITLE
scrollViewDidScroll: not called

### ISSUE THREAD

**Issue by floriankrueger** [mopub/mopub-ios-sdk#119]
Hi, we're using MoPub integration [fabric.io](http://www.fabric.io) and use `-scrollViewDidScroll:` (among others) to position some views around the `UITableView` while scrolling through the content. The moment we integrated MoPub (as described in the fabric.io setup)`-scrollViewDidScroll:` stopped being called. However, methods like `-scrollViewDidEndDecelerating:` and `-scrollViewDidEndDragging` are still being called. Everything else works as expected (ads are being displayed, opened etc.).

Does anyone else have this issue too? 
Would be great to hear from you as it blocks us from integrating MoPub.
- iOS SDK 8.2, Deployment Target 7.0
- Language: Swift

**Comment by MoJRen** [comment]
hi @floriankrueger are you using one of our AdPlacer classes?

**Comment by floriankrueger** [comment]
Yes, we're using `MPTableViewAdPlacer` and replaced all methods with their according `mp_` method.

**Comment by MoJRen** [comment]
hi @floriankrueger thanks for the info, we'll investigate

**Comment by Kelcey** [comment]
Hello @floriankrueger,

I just did a quick and simple test using Swift and the Fabric kit and scrollViewDidScroll appears to be getting called.

Of course my test was a very basic one. Could you double check your integration and email support@mopub.com if the problem persists?

Thanks!

**Comment by floriankrueger** [comment]
Hi @Kelcey, I did some restructuring after your message and found a way to fix the problem although I'm not 100% sure why it didn't work before.

We separated the `UITableViewDataSource` from the `UIViewController`. The View Controller only implemented the `UITableViewDelegate` methods (including the `scrollViewDidScroll:` method which wasn't called). The whole MoPub mechanism is part of the DataSource class, including the Ad Placer.

![screen shot 2015-04-13 at 11 29 07](https://cloud.githubusercontent.com/assets/646386/7113192/948e26cc-e1d1-11e4-833f-936862c52139.png)

Now I added the `UITableViewDelegate` methods to the former DataSource class (now appropriately called 'Companion') and forwarded the necessary methods to the ViewController in a new protocol (`DataSourceDelegate` ^^). Structured like this, everything is working fine.

![screen shot 2015-04-13 at 11 35 01](https://cloud.githubusercontent.com/assets/646386/7113230/f15326be-e1d1-11e4-8480-325e09ec92a2.png)

I have no idea whether you can reproduce this or even care to do so ;) But that's how I managed to resolve the issue. Would be interesting to know when you have an idea why the issue existed in the first place.

Thank you for your answers!

**Comment by Kelcey** [comment]
Hello @floriankrueger,

Could you send this info to support@mopub.com? 

I'll definitely take a look at it myself when I get a chance.

Thanks!
