### ISSUE TITLE
Remove native ads from tableview

### ISSUE THREAD

**Issue by ackleymi** [mopub/mopub-ios-sdk#124]
We can add ads to a tableview with 

```
- (void)loadAdsForAdUnitID:(NSString *)adUnitID targeting:(MPNativeAdRequestTargeting *)targeting;
```

but how do we then remove those ads? I want to switch between two ad cells in the same tableview for different types of content.

**Comment by alicerp** [comment]
Removing ads is currently not supported, but you can specify where ads appear in your stream via native location control: https://dev.twitter.com/mopub/ui/native-location-control

For additional questions, feel free to check out https://twittercommunity.com/c/fabric/mopub or email support@mopub.com.
