### ISSUE TITLE
MPNativeAd.h' file not found

### ISSUE THREAD

**Issue by onderozcan** [mopub/mopub-ios-sdk#133]
Dragged MopubFullSDK in to xcode ( checked copy groups if needed)

Imported into viewcontroller like  #import "MoPubSDK/MoPub.h"

When trying to compile , precompiler throw error that header file not found.

"projectName/MoPubSDK/MoPub.h:20:9: 'MPNativeAd.h' file not found"

Btw. I successfully integrated not opensource ( Fabric) SDK. But need to integrate opensource part instead of working with RTB.

**Comment by onderozcan** [comment]
Well , somehow IDE just skipped that error and throw new precompiler issue:

 'MillennialMedia/MMInterstitial.h' file not found. Somehow , i checked it has MillennialMedia under the AdNetworkSupport, but IDE just can't see it.

Tried to add/remove MopubFuLLSDK several times  but still not have a chance.

Best Regards

**Comment by linked67** [comment]
Go to build settings and add the path of Mopub folder into framawork / library search path. And make it recursive.

**Comment by onderozcan** [comment]
I've solved that issue with re-adding MoPubSDK as create  reference and selecting target on Main App scheme. 

Thank you.
