### ISSUE TITLE
Ensure that the MoPub Sample App can be inspected in Safari

### ISSUE THREAD

**Issue by ilyakam** [mopub/mopub-ios-sdk#251]
It is no longer possible to use Safari to inspect the ads that are being rendered via the MoPub Sample App on all iOS devices. This was not an issue prior to [the switch from `UIWebKit` to `WKWebKit` in version `4.11.0`](https://github.com/mopub/mopub-ios-sdk/blob/master/CHANGELOG.md#version-4110-november-10th-2016).

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:

5.4.1

#### Device model and OS Version:

All iOS devices. Tested on iPhone 6 running iOS 12.0 (`16A366`)

#### Ad Unit IDs used in reproducing the issue:

Any ad unit. Tested with `02fdbc36c0784e11a1a480f97caac6c3`

#### Steps to reproduce the behavior:

1. Install the MoPub iOS Sample App [from this page](https://developers.mopub.com/tools/sample-apps/)
1. Add an ad (tested with an _Interstitial_)
1. Load and show the newly added ad
1. [Follow these steps](https://medium.com/@mattcroak718/debugging-your-iphone-mobile-web-app-using-safari-development-tools-71240657c487) to connect the phone to the browser
1. Attempt to inspect the view with Safari

#### Expected behavior:

The option to inspect the ad in Safari should be available:

![expected](https://user-images.githubusercontent.com/183227/49322308-3f252880-f4c3-11e8-8aef-5712d1a41ca8.png)

This screenshot was taken by building the Sample App on the aforementioned target device and then inspecting it in Safari.

#### Observed behavior:

The option to inspect the ad in Safari is not available:

![observed](https://user-images.githubusercontent.com/183227/49322367-ad69eb00-f4c3-11e8-9160-ca4986f1878b.png)

#### Evidence:

See screenshots above

**Comment by jeffreycarlson** [comment]
Hi @ilyakam, 

Great question. The iOS Sample App is a production enterprise app. Inspector is only available from a debug build using a developer certificate. See more details from this StackOverflow page [here](https://stackoverflow.com/questions/37524723/use-safari-web-inspector-with-apps-compiled-for-production). 

To inspect the webview, download the MoPub sample app, please [download the source code](https://github.com/mopub/mopub-ios-sdk/releases) and build the MoPubSampleApp. You'll be able to inspect the webview then. Just tried it so can confirm this works.

**Comment by ilyakam** [comment]
Hi @jeffreycarlson ,

> To inspect the webview, please download the MoPub sample app via [source code](https://github.com/mopub/mopub-ios-sdk/releases) and build the MoPubSampleApp in Xcode.

That's exactly what I did. In fact, I mentioned as much under the **Expected behavior** heading in the OP: 

> This screenshot was taken by building the Sample App on the aforementioned target device and then inspecting it in Safari.

Based on the [StackOverflow answer that you'd linked to](https://stackoverflow.com/a/39222680/545590), it indeed says that "[t]here is no way to do that with a Distribution (enterprise, ad-hoc, app-store) certificate."

It looks like we're going to have to teach our designers how to use Xcode in order to ensure that their ads render correctly in application environments. I'm going to close this issue now, but please consider adding some functionality that would allow us to inspect the ads without having to use up the limited number of development certificates so that we could build and run the Sample App on our test devices. Thanks!

**Comment by jeffreycarlson** [comment]
@ilyakam Sounds good. Will take this feedback back to the team. 

To not use a developer certificate, you could build the sample app using the simulator and inspect the webview from there. 

Regarding creative design, are your ads going to leverage MRAID or are they strictly HTML only?

**Comment by ilyakam** [comment]
> To not use a developer certificate, you could build the sample app using the simulator and inspect the webview from there.

That's a good idea! I personally believe that simulators are much less of a hassle than physical devices for these sorts of purposes, anyway.

> are your ads going to leverage MRAID or are they strictly HTML only?

Either or -- that depends on the ads. Sometimes we may need MRAID functionality and at other times, plain HTML with some basic JavaScript sprinkled around would do the trick.

The way we use the MoPub Sample App is to verify that the ads render properly in "in-app" environments. The reason we need the Safari inspector to work is predominately in order to verify that the trackers are firing as expected. I realize that we could use other man-in-the-middle methods to figure that out (e.g., Charles Proxy). I'm just trying to optimize for the least amount of technical know-how on our designers' behalf, whose primary tool of choice is Photoshop (as opposed to an IDE, git, Xcode, etc.)

**Comment by jeffreycarlson** [comment]
For HTML creative (non-MRAID) testing, you can add the creative to the following HTML document MoPub has and inspect it in any web browser (I use Chrome with "toggle device toolbar". Just put the markup in  where `<!-- Insert Ad Markup Here -->` is.

`
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <style>
            body {
                margin: 0;
                padding: 0;
            }
        </style>
    </head>
    <body>
        
    </body>
</html>
`

For MRAID testing, we do recommend using the app but can put something together that somewhat simulates the environment if that would be helpful.

**Comment by jeffreycarlson** [comment]
Here are some basic MRAID commands we inject for 320x50s and 320x480s on iOS and Android. Note: Some of the values can change across devices.

### iOS MRAID Banner
```
window.mraidbridge.fireChangeEvent({hostSDKVersion: '4.19.0', placementType: 'inline', supports: {sms: false, tel: false, calendar: false, storePicture: false, inlineVideo: true}, state: 'default'});
window.mraidbridge.setCurrentPosition(0.0, 166.0, 320.0, 50.0);
window.mraidbridge.setDefaultPosition(0.0, 166.0, 320.0, 50.0);
window.mraidbridge.setScreenSize(320.0, 568.0);
window.mraidbridge.setMaxSize(320.0, 548.0);
window.mraidbridge.notifySizeChangeEvent(320.0, 50.0);
window.mraidbridge.fireReadyEvent();
window.mraidbridge.fireChangeEvent({viewable: true});
```

### iOS MRAID Interstitial
```
window.mraidbridge.fireChangeEvent({hostSDKVersion: '4.19.0', placementType: 'interstitial', supports: {sms: false, tel: false, calendar: false, storePicture: false, inlineVideo: true}, state: 'default'});
window.mraidbridge.setCurrentPosition(0.0, 0.0, 320.0, 568.0);
window.mraidbridge.setDefaultPosition(0.0, 0.0, 320.0, 568.0);
window.mraidbridge.setScreenSize(320.0, 568.0);
window.mraidbridge.setMaxSize(320.0, 568.0);
window.mraidbridge.notifySizeChangeEvent(320.0, 568.0);
window.mraidbridge.fireReadyEvent();
window.mraidbridge.fireChangeEvent({viewable: true});
```

### Android MRAID Banner
```
mraidbridge.setState("default")
mraidbridge.setScreenSize(360,592);mraidbridge.setMaxSize(360,252);mraidbridge.setCurrentPosition(20,187,320,50);mraidbridge.setDefaultPosition(20,187,320,50)
mraidbridge.notifySizeChangeEvent(320,50)
mraidbridge.setSupports(true,true,true,true,true)
mraidbridge.setPlacementType("inline")
mraidbridge.notifyReadyEvent();
mraidbridge.setIsViewable(true)
```

### Android MRAID Interstitial
```
mraidbridge.setState("default")
mraidbridge.setScreenSize(360,592);mraidbridge.setMaxSize(360,592);mraidbridge.setCurrentPosition(0,0,360,592);mraidbridge.setDefaultPosition(0,0,360,592)
mraidbridge.notifySizeChangeEvent(360,592)
mraidbridge.setSupports(true,true,true,true,true)
mraidbridge.setPlacementType("interstitial")
mraidbridge.notifyReadyEvent();
mraidbridge.setIsViewable(true)
```

These injected commands can be added to the `<head>` section of the HTML document within a load listener. This listener simulates the injection of mraid events after the creative is done loading, per the mraid spec requirements. Basically, on the load event of the webview, fire off these mraid functions. The additional code with the above mraid commands looks like this in a 320x50 iOS example:

```
      <!-- MoPub mraid.js file, add relative file locally -->
      <script src="mraid.js"></script>

      <!-- Simulated MRAID JS injections from MRAID Bridge for banners -->
         <script type="text/javascript">
         window.addEventListener("load", function() {
            window.mraidbridge.fireChangeEvent({hostSDKVersion: '4.19.0', placementType: 'inline', supports: {sms: false, tel: false, calendar: false, storePicture: false, inlineVideo: true}, state: 'default'});
            window.mraidbridge.setCurrentPosition(0.0, 166.0, 320.0, 50.0);
            window.mraidbridge.setDefaultPosition(0.0, 166.0, 320.0, 50.0);
            window.mraidbridge.setScreenSize(320.0, 568.0);
            window.mraidbridge.setMaxSize(320.0, 548.0);
            window.mraidbridge.notifySizeChangeEvent(320.0, 50.0);
            window.mraidbridge.fireReadyEvent();
            window.mraidbridge.fireChangeEvent({viewable: true});
         }, false);
         </script>
```

The full HTML document for an iOS 320x50 simulating mraid:

```
<!DOCTYPE html>
<html>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <style>
            body {
                margin: 0;
                padding: 0;
            }
        </style>
        
        <!-- MoPub mraid.js file, add relative file locally -->
        <script src="mraid.js"></script>

        <!-- Simulated MRAID JS injections from MRAID Bridge for banners -->
        <script type="text/javascript">
            window.addEventListener("load", function() {
                window.mraidbridge.fireChangeEvent({hostSDKVersion: '4.19.0', placementType: 'inline', supports: {sms: false, tel: false, calendar: false, storePicture: false, inlineVideo: true}, state: 'default'});
                window.mraidbridge.setCurrentPosition(0.0, 166.0, 320.0, 50.0);
                window.mraidbridge.setDefaultPosition(0.0, 166.0, 320.0, 50.0);
                window.mraidbridge.setScreenSize(320.0, 568.0);
                window.mraidbridge.setMaxSize(320.0, 548.0);
                window.mraidbridge.notifySizeChangeEvent(320.0, 50.0);
                window.mraidbridge.fireReadyEvent();
                window.mraidbridge.fireChangeEvent({viewable: true});
            }, false);
        </script>
    </head>

    <body>
    <!-- Insert Ad Markup Here -->
    </body>

</html>
```

Lastly and most importantly, save the [mraid.js](https://github.com/mopub/mopub-ios-sdk/blob/master/MoPubSDK/Resources/MRAID.bundle/mraid.js
) file from either our iOS or Android repos (they are the exact same file) to wherever you plan to save the above HTML document to. The relative url `<script src="mraid.js"></script>` from the `<head>` will include the mraid.js file automatically when viewing the HTML file from the browser. 

This will help with many of the basic mraid commands up through mraid ready but will not allow for more complex mraid commands post render needs like expand, resize, etc. For those, please do test in the SDK. For your needs, it sounds like the above will be more than enough for your basic testing needs.

**Comment by ilyakam** [comment]
This is wonderful, @jeffreycarlson. Thanks a bunch!
