### ISSUE TITLE
[CRITICAL: can't submit app] Unsupported Architecture [x86_64, i386] (can't validate for iTunes) latest framework

### ISSUE THREAD

**Issue by KAMIKAZEUA** [mopub/mopub-ios-sdk#252]
Just downloaded latest `.framework` 
https://github.com/mopub/mopub-ios-sdk/releases/tag/5.4.1

And after I archived my game in Xcode I got this warning: 

![screen shot](https://user-images.githubusercontent.com/3391456/49702573-4dc9b900-fc02-11e8-9486-52a40ae07b77.png)

**Comment by KAMIKAZEUA** [comment]
Also, I can't validate app to the App Store! 

![screen shot](https://user-images.githubusercontent.com/3391456/49702845-047b6880-fc06-11e8-9c3d-8609013806b1.png)

**Comment by wacamoe** [comment]
Hi @KAMIKAZEUA,

Can you please use the issue template found when you create a new issue:

One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:

#### Device model and OS Version:

#### Ad Unit IDs used in reproducing the issue:

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by KAMIKAZEUA** [comment]
I just dropped framework into blank project using standard documentation instructions and got this problem! 

It's blocker for me, I can't submit my app now!

**Comment by KAMIKAZEUA** [comment]
This is wrong! 

![screen shot](https://user-images.githubusercontent.com/3391456/49798666-80cb9400-fd4b-11e8-8487-48b1c2a9493c.png)

Usually valid is arm64, armv7 and armv7s

**Comment by wacamoe** [comment]
> I just dropped framework into blank project using standard documentation instructions and got this problem! It's built with wrong architecture, you just have to fix this.
> 
> It's blocker for me, I can't submit my app now!

Can you please provide your sample project? Additionally, can you fill out the above template, as well as provide the XCode version you are using?

Thanks!

**Comment by KAMIKAZEUA** [comment]
I already showed you how this should be fixed. Whats the reason to fill that bureaucratical template? BUG is clearly seen, in Valid Architectures it's specified wrong values like i386, which is not allowed for iOS. 
I already fixed this, by rebuilding framework with correct values.

**Comment by kdun** [comment]
Thank you for reporting this issue. Our investigation has discovered that XCode 10 no longer supports fat frameworks. Previously, the i386 and x86_64 simulator slices would be stripped from the app during the archiving process. We will be fixing the issue in the next release by including a simulator targeted framework and a device-only targeted framework.

For those that are still blocked, the i386 and x86_64 architectures can be removed from the Valid Architectures build setting in the MoPubSDK, and Release configuration of the MoPubSDKFramework target rebuilt to generate the device-only framework.

Thanks!

**Comment by Volodymyr-Klymenko** [comment]
Also, I wonder how this will be solved, for example I want to run my app on `Simulator` and `device`, so means I need a separate files `.framework` for each target. Right?

**Comment by kdun** [comment]
> Also, I wonder how this will be solved, for example I want to run my app on `Simulator` and `device`, so means I need a separate files `.framework` for each target. Right?

Yes, you are correct. The plan is to distribute all three variations of the framework: simulator, device, and universal. The universal framework will include the simulator and device slices, which is suitable for normal development.

For distribution to the App Store, you can replace the universal framework with the device framework either manually before archiving or a pre-build script in the scheme.

**Comment by Volodymyr-Klymenko** [comment]
Well, current universal framework builds without any issues for all architectures. 
The problem is only when archiving, so some script should be an option..

**Comment by KAMIKAZEUA** [comment]
https://github.com/mixpanel/mixpanel-iphone/issues/819#issuecomment-448023460

**Comment by meaning-matters** [comment]
Could be this: http://www.openradar.me/radar?id=6409498411401216

If you're using Carthage, add a Run Script build phase that does `carthage copy-frameworks` (as described [here](https://www.raywenderlich.com/416-carthage-tutorial-getting-started)

**Comment by KAMIKAZEUA** [comment]
I'm using only manual. 
I just downloaded mixpanel and build it without simulator architecture for now, but this should be something auto or well described in tutorials and tested on latest Xcode and submitting apps.

**Comment by KAMIKAZEUA** [comment]
@caleb-lee and how set automatically Xcode use proper `.framework` for simulator or device(same as archiving for release to App Store) ?

**Comment by kdun** [comment]
@KAMIKAZEUA You can edit your target's scheme's Archive process to run a pre-action script which copies the device-only architectures framework over the universal framework. Post-action, you can run a script to revert the changes using `git checkout -- <path to framework>/MoPubSDKFramework.framework`.

**Comment by KAMIKAZEUA** [comment]
I see.. but looks like a hack and not really good..
And what your ophinion about this: 
https://github.com/mixpanel/mixpanel-iphone/issues/819#issuecomment-448023460

**Comment by kdun** [comment]
> It's just this basically https://stackoverflow.com/questions/30547283/submit-to-app-store-issues-unsupported-architecture-x86

The script itself seems reasonable, but we haven't tried it ourselves. Honestly all these solutions will be hacky since Xcode really should be automatically slicing out the unused architectures when archiving.

**Comment by KAMIKAZEUA** [comment]
@kdun My game in on a production, works very stable and uses previous MoPub SDK 5.4.1

Today I updated to 5.5.0
https://github.com/mopub/mopub-ios-sdk/releases/tag/5.5.0

Replaced `.framework` as long as new adapters files from the official repo and all adapters SDK all latest for my game.

And when I started my game and it immediately hung.

What I noticed first previous `.framework` file size for iOS build was `4.1Mb` now, when I used framework from `iphoneos` folder it's around `18Mb`.

Don't know if I should create another bug. I tried to upgrade because in new version I have that iphoneos file.

**Comment by KAMIKAZEUA** [comment]
So, I revered to `5.4.1` and since now I will very very carefully update MoPus SDK 😨

**Comment by chauduyphanvu1** [comment]
@KAMIKAZEUA - that doesn't sound like an expected behavior. Would you mind capturing and sending us some traces showing the freeze? If you have a mini project that integrates with MoPub 5.5.0, perhaps we could investigate the issue for you.

**Comment by KAMIKAZEUA** [comment]
@chauduyphanvu1 My game is under NDA, so sharing any info would be complicated..
I can tell you that it's game build with cocos2d-x and it uses OpenGL. 

There are no any unusual traces at that point. 
Game just starts as it should, then after call init of MoPub it's dropped CPU usage to 0% and hung. So weird, Xcode just showing 0% of usage.

Sometimes, it works I'd say 1 try from 10.

If I'm not calling init of MoPub, game works as it should.

**Comment by chauduyphanvu1** [comment]
@KAMIKAZEUA - thanks for the preliminary troubleshooting. We'd recommend opening a separate issue report so this behavior could be tracked and debugged. The goal is to have our publishers upgrade to 5.5.0 and see a performance improvement. Thanks!
