### ISSUE TITLE
Debug console logs shown even if [[MoPub sharedInstance] setLogLevel:MPLogLevelOff];

### ISSUE THREAD

**Issue by KAMIKAZEUA** [mopub/mopub-ios-sdk#253]
One line summary of the issue here

- [x ] I am submitting a bug report for existing functionality
- [x ] I visited https://developers.mopub.com/ and found no answer
- [x ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.4.1
#### Device model and OS Version:
iOS 12, iPhone 8 
#### Steps to reproduce the behavior:
1. Set `[[MoPub sharedInstance] setLogLevel:MPLogLevelOff]`;
2. I'm using 6 adapters for: AdMob, AppLovin, IronSource, Tapjoy, UnityAds, Vungle.
3. When app runs init MoPub as usually per standard documentation, load ads: banners, interstitial and rewarding. 
5. Notice a lot of debug log in console coming from `Release` version of the game. 
Yes, I've set in Xcode `release` scheme for that. 

#### Expected behavior:
No any logs from any Mopub or it's networks should be displayed.

#### Observed behavior:
A lot of logs from many ad networks.

#### Evidence:

![screen shot](https://user-images.githubusercontent.com/3391456/50179534-f2897c00-030f-11e9-8284-abbeeec58215.png)

**Comment by chauduyphanvu1** [comment]
@KAMIKAZEUA, this is an expected behavior because setting `MPLogLevelOff` only applies to logs administered by the MoPub SDK itself. When you use mediation, SDKs from the mediated ad networks that use the regular `NSLog` can still utilize the console for their own log entries. MoPub does not have control over that. 

I'd recommend speaking to the ad networks in question about logging best practices for apps in production.

Vu Chau
MoPub SDK Team

**Comment by KAMIKAZEUA** [comment]
@chauduyphanvu1 I know that answer will be like that, but what will be if I manually try to access networks and try to change any properties? I don't know exactly what MoPub doing with them at the current time, initialized them or not and so on.

So it's like top control of all adapters and so should disable their logs too. 
Or tell me how I need to disable that logs manually. 
Because this is very important, game is lagging because of that! Really lagging.

**Comment by chauduyphanvu1** [comment]
Mediation SDKs _might_ provide APIs that let you silent their own logs (similar to MoPub's `[[MoPub sharedInstance] setLogLevel:MPLogLevelOff]`). If one exists, you'd call it from your app implementation. If you cannot find the APIs from the public documentation, my suggestion is to speak with an account manager or reach out to the ad networks directly for guidance. 

In the upcoming SDK release MoPub gives you the ability to silent logs from both our SDK **and** mediation adapters. That, however, still won't administer logs from mediation SDKs themselves. We can't tell another framework to stop spitting out `NSLog` entries.

**Comment by KAMIKAZEUA** [comment]
It's actually easy to disable log in any networks, most of them has such methods. 
But the reason I'm creating this bug it's - as I said already, how do I know where to call this?
Is it safe to call it? For specifically each network is it available and how will affect that logs actually? It's like better to control this from the top, so from the MoPub SDK. Don't you think so?

**Comment by KAMIKAZEUA** [comment]
@rsatrasala
I don’t understand it’s fixed?

**Comment by chauduyphanvu1** [comment]
@KAMIKAZEUA - we will begin work on it shortly for the upcoming adapter release. Stay tuned!

**Comment by KAMIKAZEUA** [comment]
So it’s not fixed, why close? Wrongly.

**Comment by KAMIKAZEUA** [comment]
@chauduyphanvu1 it's not fixed. 
It's just disables logs for mopub. 

I'm looking for - mopub disables each network adapter logs. 
So, if I set `setLogLevel:MPLogLevelOff];` for mopub, it should also disable all networks logs.
I just want that mopub, when doing all initializations of networks adapters, along with simple initialization - pass additional parameter - disable logs. Thats it.

**Comment by chauduyphanvu1** [comment]
We'll be working on this feature in the adapters. Thanks for your patience!

**Comment by KAMIKAZEUA** [comment]
Cool, buy reopen issue then! Please!
