### ISSUE TITLE
'SFSafariViewController' is only available on iOS 9

### ISSUE THREAD

**Issue by saldous** [mopub/mopub-ios-sdk#257]
SDK version 5.5.0 (5.6.0 doesn't install via cocoapods yet..). My app targets iOS 10 and up. Mopub giving me 2 warnings in build: **'SFSafariViewController' is only available on iOS 9** in file: MPAdDestinationDisplayAgent.m (lines 33 and 346)

**Comment by chauduyphanvu1** [comment]
@saldous - Thanks for letting us know! This should be a harmless warning, and it's expected because your app targets iOS 10+.

Vu Chau
MoPub SDK Team
