### ISSUE TITLE
Problem with reward video

### ISSUE THREAD

**Issue by FVivolo** [mopub/mopub-ios-sdk#259]
One line summary of the issue here

- [X] I am submitting a bug report for existing functionality
- [ X] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
Video is not showed 

#### Evidence:
2019-03-28 19:44:51.658665-0400 RuntimeIPhone[1672:217433] 
	[MoPub][MPRewardedVideoAdManager][98c29e015e7346bd9c380b1467b33850] Ad loaded
2019-03-28 19:44:51.664052-0400 RuntimeIPhone[1672:217433] 
	[MoPub][MPRewardedVideoAdManager][98c29e015e7346bd9c380b1467b33850] Attempting to show ad
2019-03-28 19:44:51.664068-0400 RuntimeIPhone[1672:217314] Error Domain=MoPubRewardedVideoAdsSDKDomain Code=-1600 "(null)"

**Comment by dravyan** [comment]
Hi @FVivolo,
 Thank you for reporting this. We are able to load and show RV ad successfully using adunit `98c29e015e7346bd9c380b1467b33850` in our testing. Could you please zip and share the project where you are seeing the issue?. We can investigate .

Thanks,
Dravya Nataraj
MoPub SDKTeam

**Comment by FVivolo** [comment]
mm is part of a game runtime clickteam for iOS, let me see how i can do it, the side part is that banner and interstitial work OK, where can i send privately this Xcode project?
