### ISSUE TITLE
Failover to next line item not working for MoPub HTML/JS creative on MoPub IOS 5.5 

### ISSUE THREAD

**Issue by foreza** [mopub/mopub-ios-sdk#260]
With the release of IOS SDK version 5.5 (and now 5.6), publishers using our API for ads have reported a spike in # of ad requests when they do not fill and return the failload.

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
IOS 5.5.0+

#### Device model and OS Version:

iPhone 6, OSV: 10.2.1
Any IOS Device

#### Xcode Version:
Version 9.4 (9F1027a) 

#### Ad Unit IDs used in reproducing the issue:
5f2a5d48bf7940f08750c9c54aaefd47 (test ad unit setup with 100% no fill and 100% fill after failover

#### Steps to reproduce the behavior:

Load up a sample project / sample app on phone using version 5.5.0 of the IOS SDK.
Proxy phone through charles to view traffic.
Use the above ad unit.
Call load/show on the ad unit (show banner)
Observe charles traffic.

#### Expected behavior:

HTML/JS creatives should failover as it does for older IOS versions when:

`document.write('<script type="text/javascript" charset="utf-8"> loaded=true; window.location="mopub://failLoad"; </script>');` 

is returned. The tag itself makes a single API call to the ad server, and looks something like this:

```
<script src="https://ads.aerserv.com/as/?plc=1064604&key=1&cb=%%CACHEBUSTER%%&lat=%%LATITUDE%%&long=%%LONGITUDE%%&adid=%eudid!&make=&model=&os=&osv=&type=&carrier=&network=&ua=%%USERAGENT%%"></script>
```

It'll either return a creative (which in this case, no issue) or the failload as mentioned above.

#### Observed behavior:

HTML/JS creative does not failover properly in IOS SDK 5.5.0+. The line item and attached creative continuously is called every 1 second if there is no fill, despite the custom network returning the failLoad as instructed. In some edge cases where fill may be lower, this results in the waterfall being completely stopped until there is fill. 

#### Evidence:

Charles log of requests (all 1 second apart) - this was done with MoPub SDK version 5.4.1, but I edited the **MP_SDK_VERSION** in MPContants.h to use version 5.5 to prove this isn't only an SDK issue:
[sample-log-1s-req.chls.zip](https://github.com/mopub/mopub-ios-sdk/files/3020500/sample-log-1s-req.chls.zip)

You can observe that (filtering by mopub) that the requests are all 1s apart and are now of all type "x-adtype": "mraid" 

Filtering by the ad network, you can also see that the failload (as specified by the documentation [here](https://developers.mopub.com/publishers/mediation/networks/custom-networks/): 

![image](https://user-images.githubusercontent.com/6035268/55199940-309d0400-5179-11e9-9d1f-4c552045db09.png)

This matches with what you instruct us to return and works with any SDK version that is older.

Yet, the MoPub ad server continues to not fail over to the next one in line unless the app is killed, the banner is killed, etc.

Charles log of requests (normal, both are 5.4.1):
[sample-log-normal-req.chls.zip](https://github.com/mopub/mopub-ios-sdk/files/3020516/sample-log-normal-req.chls.zip)

You can observe here that it fails over as intended. Nothing changed in terms of the ad response being given back, and nothing has changed. The only thing that was changed was the MoPub SDK (more specifically in this case, toggling the  **MP_SDK_VERSION** in MPContants.h).  

`
document.write('<script type="text/javascript" charset="utf-8"> loaded=true; window.location="mopub://failLoad"; </scr' + 'ipt>');
`

Would appreciate any guidance on the matter. I have reached out to MoPub support through other channels and this is what I received: 

"In MoPub SDK 5.5, we made updates to the webview that prevent JavaScript networks (or malicious JavaScript code) from overriding our APIs and delaying / manipulating functions such as loading ads and impression tracking. 
As a result of these changes, certain JavaScript networks that were manipulating our request and impression logic previously will no longer function as intended. Instead, they may not failover to the next network in the waterfall and may create a spike in ad requests."

Upon asking them further, your support team advised me to drop the SDK version. This is not acceptable as a solution, however. 

<img width="1074" alt="email-thread" src="https://user-images.githubusercontent.com/6035268/55200624-3a743680-517c-11e9-8a9c-df61e4431dba.png">

In addition, after crawling both the tickets / issues opened on the mopub-ios-sdk repo and mopub-android-sdk repo, I also learned that now, all html/js creatives will be treated as MRAID creatives moving forwards. If there needs to be an update to the creative, can you advise us as to how to modify our creative so that the failover can happen as originally expected?

I did some in-depth digging and it looks like when the creative is of type MRAID, the creative is returned back from the mopub ad server without the helper JS methods such as mopubFinishLoad / webviewDidClose, specifically this method:

`   <script
                type="text/javascript"> if (typeof htmlWillCallFinishLoad == "undefined" || !htmlWillCallFinishLoad) { if (typeof mopubFinishLoad == 'function') { window.onload = mopubFinishLoad; } }  </script>
`

We currently have a workaround where we paste this entire snippet into the creative and also make an additional <script> call which is a temporary fix. However, this is not a long term solution. Would like to work together with you folks to see if this can be quickly fixed.

Thanks! Happy to take this offline / internally if the issue is out of scope for a github issues ticket.

**Comment by dravyan** [comment]
@foreza ,
  Thank you for reporting this. This is being worked on and please refer to https://github.com/mopub/mopub-android-sdk/issues/307 for more updates and let us know if you have any questions.

Thanks,
Dravya Nataraj
MoPub SDKTeam

**Comment by foreza** [comment]
@dravyan 

Do we have a timeline for a fix so I report back to our customers?
At the moment, we're not sure when we'll see a solution and I want to know whether we should be looking into a temporary workaround.
Greatly appreciated, thanks!

**Comment by dravyan** [comment]
@foreza, I will notify the thread here as soon as I have an update on the ETA for the fix.


Thanks,
Dravya
MoPub SDKTeam

**Comment by rsatrasala** [comment]
Closing due to lack of inactivity. Please reopen a new issue if needed.
