### ISSUE TITLE
Problems about Native Video in Mopub IOS SDK

### ISSUE THREAD

**Issue by tolgatanriverdi** [mopub/mopub-ios-sdk#262]
Hi

We are trying to implement native video ads to our applications and we want to show native video ads before our video content in our applications.
I've followed the integration steps in the document but I've 3 problems I wasnt able to figure it out

1. I'm implementing native video ads manually(Without using ad placers), but in MPNativeAdDelegate protocol, I wasnt able to see a method such as adsDidFinishPlaying. So in this case we are using native video view as a small view in our screen and if user doesn't make the video as fullscreen or doesn't touch anything , I've no way to understand if the video is finished or not, is something like that possible in your SDK?

2. I wasnt able to see a skip button on Native Video Ads, is that mean native video ads are not skippable. Or only this demo video is linear?

3. In mopub panel I wasnt able to find an ad-unit to show native video ads, there is only native ads unit which shows static images and labels. For that reason I'm using the test id which shows a truck commercial.
How can I get my ad unit id for native video ad?

And as a sum up, what do you suggest for us to implement to show advertisments before our video content. Should we continue using native video ads, or should we use something like vast ads.
If your suggestion is vast ads, can you show us a tutorial about how we can do that with mopub sdk.

**Comment by chauduyphanvu1** [comment]
@tolgatanriverdi, we currently don't support pre-roll videos, which is what you are looking for (ad before content). You might still be able to achieve it, just that there's no API, official documentation, or demo code. To answer your questions:

1. There's no callback to let you know a video has completed playing. You might be able to hook into AVPlayer's own delegate (e.g. `AVPlayerItemDidPlayToEndTimeNotification`) and build out something that works for you.
2. Native videos are not skippable. They either pause or resume depending on how you interact with the ViewController (e.g. whether you go full-screen and back, or navigate away from the video view).
3. Native video is currently in beta. Publishers need to be added to the beta program in order to create native video ad units.

Vu Chau
MoPub SDK Team

**Comment by tolgatanriverdi** [comment]
Thanks for the info, so I have 2 more questions
1. Is there any other way to show vast video  ads in our mobile app without using native video ads? If there is a way can you send us a tutorial link (I saw this url but didnt understand what it is: https://developers.mopub.com/publishers/ui/creatives/direct-sold-vast/)
2. If there is no way to do that , is it possible for us to apply beta program for native video ad? If there is a way what should we do

**Comment by chauduyphanvu1** [comment]
We currently offer VAST video for interstitial and rewarded video so you don't necessarily have to use native video. It depends on what your use case is: one big difference is that interstitial and rewarded video are full-screen formats, while native video can be of either screen size. The link you referenced is for use cases where you want to serve your own house ads by uploading your own VAST responses. That can be useful as a test measure, as well.

https://developers.mopub.com/publishers/ios/interstitial/
https://developers.mopub.com/publishers/ios/rewarded-video/

**Comment by tolgatanriverdi** [comment]
Hmm, I got it. But what we need is a small screen video which will be played before our video content. So only solution for us is seems like native video. And as far as I understand,  for to be able to use native video we need to register private beta. How can we register ourselves for private beta?

**Comment by chauduyphanvu1** [comment]
You will need to be whitelisted by an account manager to use MoPub's Marketplace demand for native video ads.

**Comment by tolgatanriverdi** [comment]
Do you know how can I reach to a marketplace account manager, I've sent email to support@mopub but there is no response

**Comment by chauduyphanvu1** [comment]
@tolgatanriverdi, I don't have visibility into how that process is done.
