### ISSUE TITLE
Crash MPRateLimitManager.m line 41 #269

### ISSUE THREAD

**Issue by xuzepei** [mopub/mopub-ios-sdk#277]
Hi, I noticed you have fixed this crash in 5.7.1. 

Please also notify the Google Mobile Ads Team to upgrade GoogleMobileAdsMediationMoPub to your latest SDK.

_Originally posted by @rsatrasala in https://github.com/mopub/mopub-ios-sdk/issues/269#issuecomment-504565058_

**Comment by chauduyphanvu** [comment]
@xuzepei, thanks for staying on top of this. The Mobile Ads team has its own mediation certification program and deadline, so upon certifying MoPub's 5.7.1 SDK they will release the new adapters to pull that version of our SDK. Feel free to reach out to their team [over here](https://github.com/googleads/googleads-mobile-ios-mediation) if you have any questions!

Vu Chau
MoPub SDK Team

**Comment by rsatrasala** [comment]
Informed Google team. No other Action Items for MoPub. So Closing.
