### ISSUE TITLE
Crash MPMediationManager.m

### ISSUE THREAD

**Issue by bkorda** [mopub/mopub-ios-sdk#278]
One line summary of the issue here

- [v] I am submitting a bug report for existing functionality
- [v] I visited https://developers.mopub.com/ and found no answer
- [v] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [v] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

Implement CustomEvent
```
mopubConfiguration.additionalNetworks = @[loopMeConf];
[mopubConfiguration setNetworkConfiguration:@{ @"viewController" : self } forMediationAdapter:@"LoopMeAdapterConfiguration"];
mopubConfiguration.loggingLevel = MPBLogLevelInfo;
mopubConfiguration.allowLegitimateInterest = YES;

[[MoPub sharedInstance] initializeSdkWithConfiguration:mopubConfiguration completion:nil];
```
EXC_BAD_ACCESS on line 122 in Crash MPMediationManager.m
```
// Retrieve the full set of initialization parameters.
        NSDictionary * initializationParams = [self parametersForAdapter:adapterInfoProvider overrideConfiguration:configurations[NSStringFromClass(adapterInfoProviderClass)]];
```
I found out that NSStringFromClass() doesn't work.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
<img width="443" alt="mopub" src="https://user-images.githubusercontent.com/2910650/61353550-c2d82d80-a878-11e9-9867-331001c973d4.png">

**Comment by dravyan** [comment]
@bkorda,
 Thank you for reporting this. From the code snippet above it looks like the array of custom adapter configuration class name is not passed as recommended to  `.additionalNetwork`. You can refer [here](https://developers.mopub.com/publishers/ios/initialize/#initializing-custom-ad-networks-not-listed-on-supported-mediation-partners)

You can use below example,
```
config.additionalNetworks = [NSArray arrayWithObject:MockAdapterConfiguration.class]
```

Thanks,
Dravya Nataraj
MoPub SDKTeam

**Comment by bkorda** [comment]
Thank you,
It works. I think better to change your wiki, it's not clear

`sdkConfig.additionalNetworks(NSArray of class names);`

Thank you so much.
