### ISSUE TITLE
Rewarded video Test ad is not being shown

### ISSUE THREAD

**Issue by Yuri-Soomla** [mopub/mopub-ios-sdk#284]
Mopub test rewarded video ad has two rewards while you code has one limitation.
Please fix. 

https://github.com/mopub/mopub-ios-sdk/blob/master/MoPubSDK/RewardedVideo/Internal/MPRewardedVideoAdManager.m#L127

**Comment by dravyan** [comment]
Hi @Yuri-Soomla,
Thank you for your question. With the adunit you are testing, the sample app should hit the else loop [here](https://github.com/mopub/mopub-ios-sdk/blob/b6e6d91a0867c183e07aa53b1afab0c04cf8175c/MoPubSDK/RewardedVideo/Internal/MPRewardedVideoAdManager.m#L139) as the rewards are available for the adunit on MoPub dashboard.
 
[This](https://github.com/mopub/mopub-ios-sdk/blob/master/MoPubSDK/RewardedVideo/Internal/MPRewardedVideoAdManager.m#L127) is only called if the rewards are not set for the adunit. Then we follow the single currency approach. 

Thanks,
Dravya Nataraj
MoPub SDKTeam
