### ISSUE TITLE
Apple no longer accepting UIWebView in submissions

### ISSUE THREAD

**Issue by rob-keepsafe** [mopub/mopub-ios-sdk#285]
Apple is no longer accepting binary submissions that reference the `UIWebView` APIs

<img width="672" alt="Screen Shot 2019-09-04 at 4 48 53 PM" src="https://user-images.githubusercontent.com/30269720/64290742-ac735780-cf34-11e9-8767-444f7d1e57f4.png">

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:

latest master branch

**Comment by jeffreycarlson** [comment]
@rob-keepsafe Thank you for the note. Apologies to you for having to encounter this alert!

We've already been working on removing the last remaining UIWebView code from the SDK. Most of our SDK has used WKWebView exclusively since version 4.11.0 so the necessary changes are few. We'll keep this page up-to-date with the timing of a release when those details are available.

**Comment by chauduyphanvu** [comment]
@rob-keepsafe, this issue should now be resolved with the [5.9.0 release](https://github.com/mopub/mopub-ios-sdk/blob/master/CHANGELOG.md#version-590-september-16-2019) of the MoPub iOS SDK. We've removed all UIWebView code from the SDK. 

Vu Chau
MoPub SDK Team

**Comment by rob-keepsafe** [comment]
Thanks for the quick changes, @chauduyphanvu 🙌  We'll test in an upcoming release

I'll go ahead and close this for now since I can't find any `UIWebView*` code in the repo now. (closed via 853cbf22ef14c3f5e4aedcf6f00c944d3a2b9843)

**Comment by chauduyphanvu** [comment]
@rob-keepsafe, thanks for flagging that. We're aware of the issue, and have been in touch with Avid for that. They will need to remove their `UIWebView` code in a future SDK; meanwhile, please remove their binary from disk and rebuild your app.
