### ISSUE TITLE
Mopub 5.9.0 SDK does not build

### ISSUE THREAD

**Issue by wimbledon** [mopub/mopub-ios-sdk#287]
Cocoapod update from 5.8.0 to 5.9.0.
MOPUBNativeVideoImpressionAgent.h is missing.
And the SDK does not build.

**Comment by dravyan** [comment]
@wimbledon, thank you for reporting the issue. We have not seen this issue in our internal testing. Could you provide more details on your app's use case which needs `MOPUBNativeVideoImpressionAgent`?. This is not a Public API class and Publishers should not be using this class.  Instead, we can provide a recommendation based on your use case.

Thanks,
Dravya Nataraj
MoPub SDK Team

**Comment by wimbledon** [comment]
Xcode Version 10.2.1 (10E1001)
Deployment Target: 9.0
SWIFT_VERSION=5.0

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!
install! 'cocoapods', :deterministic_uuids => false

**Build Error:**
Pods/mopub-ios-sdk/MoPubSDK/NativeVideo/Internal/MOPUBNativeVideoImpressionAgent.h: No such file or directory

**Comment by wimbledon** [comment]
@dravyan Looks like MOPUBNativeVideoImpressionAgent.h is used in 5.8.0 SDK but not in 5.9.0.
I was able to resolve the issue by `pod deintegrate` before `pod update`
