### ISSUE TITLE
x-networktype requests native on a banner request clarification

### ISSUE THREAD

**Issue by mmdock** [mopub/mopub-ios-sdk#288]
Just need to ask a clarifying question, and if this is an issue, can file a proper issue message on this thread.

i am seeing the following in the debug log of a banner ad request:

```
                "x-nativeparams" = "{\"adHeight\":50,\"adUnitID\":\" {{my admob ad id}}\",\"adWidth\":320}";
                "x-networktype" = "admob_native";
                "x-refreshtime" = 30;
                "x-width" = 375;
            };
        }
    );
    "adunit-format" = banner;
```

I see that the `x-networktype` is an "admob_native" even though I am requesting a banner ad.  Is this mistaken?  I am trying to figure out why i cannot get ads to fill in.  If there is documentation that can help me learn this, please link it to me.  I have looked already to no success. 

Facebook ads and Mopub ads i have mediated work fine.  Only admob doesn't seem to show.

**Comment by chauduyphanvu** [comment]
@mmdock, `admob_native` is a name we gave to the network connection internally. It doesn't hold a special meaning and doesn't denote it's for a native ad. The name [comes from the adapter](https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/GoogleAdMobAdapterConfiguration.m#L56) and is simply a hard-coded String.

If you don't get ads for banners, feel free to create a GitHub issue and attach the necessary information we ask for in our issue template. We should then be able to assist you.

Vu Chau
MoPub SDK Team

**Comment by mmdock** [comment]
@chauduyphanvu thanks for the quick response.  I'll do some more testing on my end before finalizing if this is an issue or not.
