### ISSUE TITLE
New version of MoPub-Applovin-Adapters required

### ISSUE THREAD

**Issue by dtorres** [mopub/mopub-ios-sdk#296]
AppLovin has released a new SDK (6.9.5), fixing a crash in their previous version which is the one currently supported (6.9.4) by `MoPub-Applovin-Adapters`.

Cocoapods constraints won't let us update to the fixed version. please publish a more lax requirement (~> 6.9) or a new version.

Thank you 

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

**Comment by chauduyphanvu** [comment]
@dtorres, v6.9.0.5 adapter working with v6.9.5 AppLovin SDK is now available via https://github.com/mopub/mopub-ios-mediation/commit/247871fc631f9b895e9fbf94a408535998718ffd. CocoaPods distribution should be available in the next few minutes.

Vu Chau
MoPub Support Team
