### ISSUE TITLE
Rewarded Video Ads Overview  no display  ，Stuck at Attempting to show ad

### ISSUE THREAD

**Issue by tomato313** [mopub/mopub-ios-sdk#299]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
2019-10-28 15:50:48.116721+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MPConsentManager] Attempting to synchronize consent state
2019-10-28 15:50:48.116794+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MPConsentManager] Consent synchronization complete: GDPR not applicable, consent synchronization will complete immediately
2019-10-28 15:50:48.116876+0800 mopub-demoTest[2139:1077142] 🌹🌹🌹[MoPub] SDK 初始化完成
2019-10-28 15:50:48.116912+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MoPub] SDK initialized and ready to display ads.
	Initialized adapters:
	No adapters initialized
2019-10-28 15:50:48.117360+0800 mopub-demoTest[2139:1077139] 
	[MoPub][MPRewardedVideoAdManager][8f000bd5e00246de9c789eed39ff6096] Attempting to load ad
2019-10-28 15:50:48.137390+0800 mopub-demoTest[2139:1077139] 
	[MoPub][MPViewabilityTracker] MPViewabilityAdapterAvid was found.
2019-10-28 15:50:48.137691+0800 mopub-demoTest[2139:1077139] 
	[MoPub][MPViewabilityTracker] MPViewabilityAdapterMoat was found.
2019-10-28 15:50:48.157757+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MPGeolocationProvider] Will not start location updates: the application is not authorized for location services.
2019-10-28 15:50:48.158629+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MPAdServerCommunicator] Requesting an ad from Adserver: https://ads.mopub.com/m/ad
	{"ch":"0","av":"1.0","dn":"iPhone9,1","mid":"DE3D9264-C6D4-40F6-BD87-061FD39811B8","force_gdpr_applies":"0","vv":"3","ats":"6","gdpr_applies":"0","h":"1334","udid":"ifa:XXXX","nv":"5.9.0","ct":"2","w":"750","v":"8","id":"8f000bd5e00246de9c789eed39ff6096","mr":"1","cn":"中国移动","bundle":"master.mopub-demoTest","z":"+0800","cw":"0","sc":"2.0","current_consent_status":"unknown","o":"p"}
2019-10-28 15:50:48.178057+0800 mopub-demoTest[2139:1077139] 
	[MoPub][MPGeolocationProvider] Location authorization status changed to: 0
2019-10-28 15:50:48.178127+0800 mopub-demoTest[2139:1077139] 
	[MoPub][MPGeolocationProvider] Stopping any scheduled location updates.
2019-10-28 15:50:48.380245+0800 mopub-demoTest[2139:1076962] [ProcessSuspension] 0x1037e5500 - ProcessAssertion::processAssertionWasInvalidated()
2019-10-28 15:50:48.380967+0800 mopub-demoTest[2139:1076962] [ProcessSuspension] 0x1037e5560 - ProcessAssertion::processAssertionWasInvalidated()
2019-10-28 15:50:50.777208+0800 mopub-demoTest[2139:1077147] 
	[MoPub][MPAdServerCommunicator] Adserver responded with:
{
    "ad-responses" =     (
                {
            content = " <!DOCTYPE html> <html> <head>    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">  <style type='text/css'> .mp_center { position: fixed; top: 50%; left: 50%; margin-left: -0px !important; margin-top: -0px !important; } </style>  <link rel=\"stylesheet\" type=\"text/css\" href=\"https://d1zg4cyg8u4pko.cloudfront.net/v2/styles.min.css?v=1_18197\">  </head> <body style=\"margin:0;padding:0;\">  <div id=\"mpVideoDiv\"> </div> <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script> <script src=\"https://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.mobile.min.js\"></script> <script src=\"https://d1zg4cyg8u4pko.cloudfront.net/v2/vast2html5.min.js?v=1_18197\"></script>  <textarea style=\"display:none\" id=\"vastXMLContent\"> &lt;VAST version=&quot;2.0&quot;&gt;\n  &lt;Ad id=&quot;1&quot;&gt;\n    &lt;InLine&gt;\n      &lt;AdSystem&gt;MoPub&lt;/AdSystem&gt;\n      &lt;AdTitle&gt;MoPub Video Test Ad&lt;/AdTitle&gt;\n      &lt;Impression&gt;\n        &lt;![CDATA[https://d30x8mtr3hjnzo.cloudfront.net/client/images/vastimp1x1.png?1572249050127]]&gt;\n      &lt;/Impression&gt;\n      &lt;Creatives&gt;\n        &lt;Creative&gt;\n          &lt;Linear&gt;\n            &lt;Duration&gt;00:00:30&lt;/Duration&gt;\n            &lt;VideoClicks&gt;\n              &lt;ClickThrough&gt;\n                &lt;![CDATA[mopubnativebrowser://navigate?url=http%3A%2F%2Fwww.mopub.com]]&gt;\n              &lt;/ClickThrough&gt;\n            &lt;/VideoClicks&gt;\n            &lt;MediaFiles&gt;\n              &lt;MediaFile delivery=&quot;progressive&quot; type=&quot;video/mp4&quot; bitrate=&quot;325&quot; width=&quot;640&quot; height=&quot;360&quot;&gt;\n                &lt;![CDATA[https://d2al1opqne3nsh.cloudfront.net/videos/corgi_30s_640x360_baseline_30.mp4]]&gt;\n              &lt;/MediaFile&gt;\n            &lt;/MediaFiles&gt;\n          &lt;/Linear&gt;\n        &lt;/Creative&gt;\n        &lt;Creative&gt;\n          &lt;CompanionAds&gt;\n            &lt;Companion width=&quot;640&quot; height=&quot;360&quot;&gt;\n              &lt;StaticResource creativeType=&quot;image/jpeg&quot;&gt;\n                &lt;![CDATA[https://d2al1opqne3nsh.cloudfront.net/images/igetbeggin_640x360.jpg]]&gt;\n              &lt;/StaticResource&gt;\n              &lt;TrackingEvents&gt;\n                &lt;Tracking event=&quot;creativeView&quot;&gt;\n                  &lt;![CDATA[mopubnativebrowser://navigate?url=https://www.mopub.com/?q=companionClickThrough640x360]]&gt;\n                &lt;/Tracking&gt;\n              &lt;/TrackingEvents&gt;\n              &lt;CompanionClickThrough&gt;\n                &lt;![CDATA[mopubnativebrowser://navigate?url=https://www.mopub.com/?q=companionClickThrough640x360]]&gt;\n              &lt;/CompanionClickTh2019-10-28 15:50:50.784640+0800 mopub-demoTest[2139:1076962] [framework] CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'master.mopub-demoTest'
2019-10-28 15:50:50.785945+0800 mopub-demoTest[2139:1076962] [framework] CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'master.mopub-demoTest'
rough&gt;\n            &lt;/Companion&gt;\n          &lt;/CompanionAds&gt;\n        &lt;/Creative&gt;\n      &lt;/Creatives&gt;\n    &lt;/InLine&gt;\n  &lt;/Ad&gt;\n&lt;/VAST&gt; </textarea>  <script type=\"text/javascript\"> var urls = new Array(); var i = 0;  var moConfig = { clickSelector: '#mpVideoDiv', clickTracking: [\"https://ads.mopub.com/m/aclk?appid=&cid=4652bd83d89a40c5a4e276dbf101499f&city=&ckv=2&country_code=HK&cppck=CB44F&current_consent_status=unknown&dev=iPhone9%2C1&exclude_adgroups=b4148ea9ed7b4003b9d7c1e61036e0b1&gdpr_applies=0&id=8f000bd5e00246de9c789eed39ff6096&is_mraid=0&os=iOS&osv=13.1.2&priority=5&req=9e900b787795404b892854ed5fd9b905_005ed7c700732bc5&reqt=1572249050.0&rev=0&udid=ifa%3A96636776-C796-496F-9B42-91F339346E45&video_type=\"], impression: urls, is_rewarded_video:  true  };  moConfig.vastSelector = \"#vastXMLContent\";  moConfig.disableViewabilityIAS =  false;  moConfig.sampleViewabilityIAS =  false;  moConfig.disableViewabilityMoat =  false;  moConfig.sampleViewabilityMoat =  false;  moConfig.viewabilityTrackersJson = '{\"moat\":\"https://z.moatads.com/mopubinapphtmvideo468906546585/moatad.js#moatClientLevel1=681c46c842984cc798f2202fa1da2cfb&moatClientLevel2=8f000bd5e00246de9c789eed39ff6096&moatClientLevel3=video&moatClientSlicer1=Rewarded%20Video\"}'; mpVast.init(moConfig); </script>  </body> </html> ";
            metadata =             {
                "content-type" = "text/html; charset=UTF-8";
                impdata =                 {
                    "adgroup_id" = b4148ea9ed7b4003b9d7c1e61036e0b1;
                    "adgroup_name" = "Rewarded Video Sample Ad";
                    "adgroup_priority" = 6;
                    "adgroup_type" = gtee;
                    "adunit_format" = "Rewarded Video";
                    "adunit_id" = 8f000bd5e00246de9c789eed39ff6096;
                    "adunit_name" = "iOS Sample App Rewarded Video";
                    country = HK;
                    currency = USD;
                    id = "9e900b787795404b892854ed5fd9b905_005ed7c700732bc5";
                    precision = "publisher_defined";
                    "publisher_revenue" = "5e-05";
                };
                imptrackers =                 (
                    "https://ads.mopub.com/m/imp?appid=&cid=4652bd83d89a40c5a4e276dbf101499f&city=&ckv=2&country_code=HK&cppck=05EFF&current_consent_status=unknown&dev=iPhone9%2C1&exclude_adgroups=b4148ea9ed7b4003b9d7c1e61036e0b1&gdpr_applies=0&id=8f000bd5e00246de9c789eed39ff6096&is_mraid=0&os=iOS&osv=13.1.2&priority=5&req=9e900b787795404b892854ed5fd9b905_005ed7c700732bc5&reqt=1572249050.0&rev=0.000050&udid=ifa%3A96636776-C796-496F-9B42-91F339346E45&video_type="
                );
                "x-ad-timeout-ms" = 30000;
                "x-adgroupid" = b4148ea9ed7b4003b9d7c1e61036e0b1;
                "x-adtype" = "rewarded_video";
                "x-before-load-url" = "https://ads.mopub.com/m/attempt?cid=4652bd83d89a40c5a4e276dbf101499f&country_code=HK&cppck=FC02B&current_consent_status=unknown&gdpr_applies=0&id=8f000bd5e00246de9c789eed39ff6096&logged_server_side=0&pf=1&pfs=&req=9e900b787795404b892854ed5fd9b905_005ed7c700732bc5&reqt=1572249050.0&rtc=0";
                "x-browser-agent" = 0;
                "x-clickthrough" = "https://ads.mopub.com/m/aclk?appid=&cid=4652bd83d89a40c5a4e276dbf101499f&city=&ckv=2&country_code=HK&cppck=CB44F&current_consent_status=unknown&dev=iPhone9%2C1&exclude_adgroups=b4148ea9ed7b4003b9d7c1e61036e0b1&gdpr_applies=0&id=8f000bd5e00246de9c789eed39ff6096&is_mraid=0&os=iOS&osv=13.1.2&priority=5&req=9e900b787795404b892854ed5fd9b905_005ed7c700732bc5&reqt=1572249050.0&rev=0&udid=ifa%3A96636776-C796-496F-9B42-91F339346E45&video_type=";
                "x-creativeid" = 4652bd83d89a40c5a4e276dbf101499f;
                "x-orientation" = d;
                "x-precacherequired" = 1;
                "x-refreshtime" = 30;
                "x-rewarded-currencies" =                 {
                    rewards =                     (
                                                {
                            amount = 1;
                            name = lives;
                        },
                                                {
                            amount = 10;
                            name = Coins;
                        }
                    );
                };
                "x-vastvideoplayer" = 1;
            };
        }
    );
    "adunit-format" = "rewarded_video";
    "backoff_ms" = 0;
    "backoff_reason" = filled;
    "x-next-url" = "https://ads.mopub.com/m/ad?ac=0&ats=6&av=1.0&bundle=master.mopub-demoTest&ch=0&cn=%E4%B8%AD%E5%9B%BD%E7%A7%BB%E5%8A%A8&cppck=812FB&ct=2&current_consent_status=unknown&cw=0&dn=iPhone9%2C1&exclude=b4148ea9ed7b4003b9d7c1e61036e0b1&force_gdpr_applies=0&gdpr_applies=0&h=1334&id=8f000bd5e00246de9c789eed39ff6096&mid=DE3D9264-C6D4-40F6-BD87-061FD39811B8&mr=1&nv=5.9.0&o=p&request_id=9e900b787795404b892854ed5fd9b905_005ed7c700732bc5&rtc=1&sc=2.0&tqr=Xbad2qVlG91FbAf0ElPPIKqN1PXi69EolOVAhw&udid=ifa%3A96636776-C796-496F-9B42-91F339346E45&v=8&vv=3&w=750&z=%2B0800";
    "x-request-id" = "9e900b787795404b892854ed5fd9b905_005ed7c700732bc5";
}
2019-10-28 15:50:50.829420+0800 mopub-demoTest[2139:1077147] 
	[MoPub][MPRewardedVideoAdManager] Rewarded video ad is fetching ad network type: rewarded_video
2019-10-28 15:50:50.829640+0800 mopub-demoTest[2139:1077147] 
	[MoPub][MPRewardedVideoAdapter] Looking for custom event class named MPMoPubRewardedVideoCustomEvent.
2019-10-28 15:50:50.829838+0800 mopub-demoTest[2139:1077147] 
	[MoPub][MPMoPubRewardedVideoCustomEvent][8f000bd5e00246de9c789eed39ff6096] Adapter MPMoPubRewardedVideoCustomEvent attempting to load ad
2019-10-28 15:50:51.459098+0800 mopub-demoTest[2139:1077139] 
	[MoPub][MPAdServerCommunicator] Successfully sent before load URL
2019-10-28 15:50:53.095028+0800 mopub-demoTest[2139:1076962] 🌹🌹🌹视频加载完毕
2019-10-28 15:50:53.095682+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRController] MRController - loading MoPub URL: mopub://precacheComplete
2019-10-28 15:50:53.095810+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRController] Injecting initial JavaScript state.
2019-10-28 15:50:53.095886+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRBridge] mraidbridge.fireChangeEvent({hostSDKVersion: '5.9.0', placementType: 'interstitial', supports: {sms: false, tel: false, calendar: false, storePicture: false, inlineVideo: true}, state: 'default'})
2019-10-28 15:50:53.095988+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRBridge] mraidbridge.setCurrentPosition(0.0, 20.0, 375.0, 647.0)
2019-10-28 15:50:53.096029+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRController] Current Position: {{0, 20}, {375, 647}}
2019-10-28 15:50:53.096094+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRBridge] mraidbridge.setDefaultPosition(0.0, 0.0, 1.0, 1.0)
2019-10-28 15:50:53.097673+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRController] Default Position: {{0, 0}, {1, 1}}
2019-10-28 15:50:53.097960+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRBridge] mraidbridge.setScreenSize(375.0, 667.0)
2019-10-28 15:50:53.098655+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRController] Screen Size: {375, 667}
2019-10-28 15:50:53.099036+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRBridge] mraidbridge.setMaxSize(375.0, 647.0)
2019-10-28 15:50:53.099220+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRController] Max Size: {375, 647}
2019-10-28 15:50:53.099348+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRController] Ad Size (Size Event): {375, 647}
2019-10-28 15:50:53.099694+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRBridge] mraidbridge.notifySizeChangeEvent(375.0, 647.0)
2019-10-28 15:50:53.099732+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MRBridge] mraidbridge.fireReadyEvent()
2019-10-28 15:50:53.099764+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MPMoPubRewardedVideoCustomEvent][8f000bd5e00246de9c789eed39ff6096] Adapter MPMoPubRewardedVideoCustomEvent sucessfully loaded ad
2019-10-28 15:50:53.101059+0800 mopub-demoTest[2139:1077142] 
	[MoPub][MPRewardedVideoAdManager][8f000bd5e00246de9c789eed39ff6096] Ad loaded
2019-10-28 15:50:53.114293+0800 mopub-demoTest[2139:1077143] 
	[MoPub][MRBridge] Trying to process command: mraid://usecustomclose?shouldUseCustomClose=true
2019-10-28 15:50:53.114575+0800 mopub-demoTest[2139:1077147] 
	[MoPub][MRBridge] mraidbridge.nativeCallComplete('usecustomclose')
2019-10-28 15:51:18.278664+0800 mopub-demoTest[2139:1076962] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2019-10-28 15:51:18.280133+0800 mopub-demoTest[2139:1076962] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
2019-10-28 15:59:21.672964+0800 mopub-demoTest[2139:1077139] 
	[MoPub][MPRewardedVideoAdManager][8f000bd5e00246de9c789eed39ff6096] Attempting to show ad
2019-10-28 16:01:26.060393+0800 mopub-demoTest[2139:1077139] 
	[MoPub][MPGeolocationProvider] Stopping any scheduled location updates.
2019-10-28 16:01:26.167424+0800 mopub-demoTest[2139:1076962] Can't end BackgroundTask: no background task exists with identifier 3 (0x3), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@tomato313, ad unit ID 8f000bd5e00246de9c789eed39ff6096 played without issues in the MoPub iOS sample app (it's in fact our test ad unit ID for rewarded video). That indicates what you are encountering might be an integration/implementation issue. Feel free to share your test app to support@mopub.com, and we'll be happy to take a look!

Vu Chau
MoPub Support Team

**Comment by tomato313** [comment]
thank you for your answer

**Comment by tomato313** [comment]
@chauduyphanvu  thank you for your answer
