### ISSUE TITLE
Dead Lock In the MPTimer.m(Non-thread safe)

### ISSUE THREAD

**Issue by nonsense0biubiu** [mopub/mopub-ios-sdk#300]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.9.0
#### Device model and OS Version:
iOS13.1
#### Xcode Version:
Xcode11.1
#### Ad Unit IDs used in reproducing the issue:
irrelevant
#### Steps to reproduce the behavior:
1.Initialize Mopub Sdk in an asynchronous child thread 
2.show the Mopub Interstitial Ad in the main thread
3.Then under certain circumstances, the MPTimer will cause Dead Lock!
![E2ED36B0-FC5E-4D90-A742-D412A231A087](https://user-images.githubusercontent.com/35053575/68461985-83c65180-0246-11ea-9b0e-88c10e7d5caa.png)
The call stack is missing :(  sorry.
but the ultimate cause of the dead lock is the` dispatch_once`.
The conditions of dead lock :
1.(Asynchronous child thread)Mopub's initialization method first accesses MPTimer's Init method.
2.(Main thread)Mopub's ad calls the Show method(eg: showFromViewController:), and Also the show method will access the MPTimer Class.However, at the same time MPTimer's `init method` is not completed. According to the characteristics of the dispatch_once method, the main thread will wait the dispatch_once completed, and at the same time,the MPTimer will invoke `dispatch_sync(dispatch_get_main_queue(), mainThreadOperation);` 
![image](https://user-images.githubusercontent.com/35053575/68461345-fcc4a980-0244-11ea-921f-a5254eb5875b.png)
Finally, everyone is waiting for each other.

**Comment by chauduyphanvu** [comment]
@nonsense0biubiu, thanks for letting us know. I'll relay the details to the rest of the team. In the meantime, if you can send over a sample project that reproduces the issue, that'll help with debugging!

Vu Chau
MoPub Team

**Comment by nonsense0biubiu** [comment]
> @nonsense0biubiu, thanks for letting us know. I'll relay the details to the rest of the team. In the meantime, if you can send over a sample project that reproduces the issue, that'll help with debugging!
> 
> Vu Chau
> MoPub Team

how can I send you the  sample project?

**Comment by chauduyphanvu** [comment]
@nonsense0biubiu, feel free to zip it up and send us a link. If the project is confidential, feel free to email it to support@mopub.com and reference this GitHub Issues thread. We'll be right with you!

**Comment by chauduyphanvu** [comment]
@nonsense0biubiu, we believe we identified the cause of the issue and will add a fix in the upcoming SDK release.
