### ISSUE TITLE
[MPAdServerURLBuilder(Ad) locationInformationDictionary] case Crash(Multithreading)

### ISSUE THREAD

**Issue by nonsense0biubiu** [mopub/mopub-ios-sdk#302]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.9.0
#### Device model and OS Version:
13.1
#### Xcode Version:
11.1
#### Evidence:
![image](https://user-images.githubusercontent.com/35053575/68463055-c6892900-0248-11ea-882b-7303e34105eb.png)

Prerequisite: All operations of the Mopub SDK are placed asynchronously within the child thread.
The local did not reproduce, but my partner and I guessed that multithreaded access to the `singletonForClass` method caused `klass` or `singleton` to be released.
![image](https://user-images.githubusercontent.com/35053575/68463162-018b5c80-0249-11ea-9733-69b40bfe99fa.png)

**Comment by dravyan** [comment]
@nonsense0biubiu , thank you for letting us know. I will relay the information to our internal team and see what we can do to resolve it.

Thanks,
Dravya Nataraj
MoPub Team

**Comment by dravyan** [comment]
@nonsense0biubiu, the fix for the issue has been applied to our SDK and will be available in the next release. I will notify this thread once the fixed version is released.

Thanks,
Dravya Nataraj
MoPub Team

**Comment by chauduyphanvu** [comment]
This should be fixed in the 5.12.0 SDK release. Let us know if you continue seeing the issue!

Vu Chau
MoPub Team
