### ISSUE TITLE
Compile problem with "excluding native" zipped source file of the SDK 5.10.0

### ISSUE THREAD

**Issue by sgabello** [mopub/mopub-ios-sdk#305]
The `MoPub Base SDK Excluding Native.zip` archive of the SDK 5.10.0 referenced [here](https://developers.mopub.com/publishers/ios/get-started/#step-1-download-the-mopub-ios-sdk), includes this [file](MoPubSDK/Internal/Utility/Categories/MPNativeAdError+VAST.h) which imports `MPNativeAdError.h`, which is not included in the archive, causing Xcode to throw an exception at compile time.

**Comment by chauduyphanvu** [comment]
@sgabello, thanks for letting us know! Let me relay this to the rest of the team and we'll issue a fix.

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
@sgabello, to provide an update, we've addressed build issues with the "excluding native" zipped source internally. Barring any other technical issues, the fix should go out in an upcoming SDK release.

**Comment by sgabello** [comment]
Cheers, thanks for the update!
