### ISSUE TITLE
Banner ad documentation regarding constraints and rotation.

### ISSUE THREAD

**Issue by pangia** [mopub/mopub-ios-sdk#306]
Documentation needs updating to include examples for iPhoneX/XR/etc. (devices with safe area.) All documentation is very old and does not take into account changes after iOS10.

Need details on when to set constraints for main view to account for banner view. When done in ViewDidLoad like in current documentation, the view has not yet adjusted for the safe space and banners are off. When done in viewWillAppear we get some random constraint issues.

Need direction on the official way to adjust the screen to account for the bannerView.

*This also needs to be cleared up in documentation for when device is rotated. The current docs reference very old/deprecated UIViewController methods.

Thanks!
 
- [X] I visited https://developers.mopub.com/ and found no answer
- [X ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ X] I checked to make sure that this issue has not already been filed

**Comment by sgabello** [comment]
I second this ticket. Documentation needs a deep and detailed review. Code examples refer to APIs that have been marked as deprecated. For example: `MOPUB_BANNER_SIZE` is marked as deprecated, but used constantly throughout the documentation.

**Comment by dravyan** [comment]
@pangia , thank you for reporting this. Please refer to the [`loadAdWithMaxAdSize`](https://github.com/mopub/mopub-ios-sdk/blob/853cbf22ef14c3f5e4aedcf6f00c944d3a2b9843/MoPubSDK/MPAdView.h#L124) where you can specify the maximum desired ad size to load. Then when the adView is loaded, the callback [`adViewDidLoadAd`](https://github.com/mopub/mopub-ios-sdk/blob/42bd0a4a365bacbbc9c4fe56fcec16c57629fd74/MoPubSDK/MPAdViewDelegate.h#L60) will specify the actual size of the ad view just loaded so you can resize the screen if necessary.
We will update the documentation to reflect these latest APIs.

Thanks,
Dravya Nataraj
MoPub Team
