### ISSUE TITLE
Video ads are displayed in the game, but the game is not suspended

### ISSUE THREAD

**Issue by LongJiangSB** [mopub/mopub-ios-sdk#308]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.10.0
#### Device model and OS Version:
iPhone 8，iOS 13
#### Xcode Version:
11.3
#### Ad Unit IDs used in reproducing the issue:
Ads is can show
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
use 
```
if ([MPRewardedVideo hasAdAvailableForAdUnitID:adUnitID]) {
    //        NSArray * rewards = [MPRewardedVideo availableRewardsForAdUnitID:self.adConfig.adUnitId];
    MPRewardedVideoReward * reward = [MPRewardedVideo selectedRewardForAdUnitID:adUnitID];
    [MPRewardedVideo presentRewardedVideoAdForAdUnitID:adUnitID fromViewController:aVC withReward:reward customData:@""];
    break;
}
```
ad is showing.
but game not suspended.

#### Expected behavior:
As concisely as possible, describe the expected behavior.
game is suspended

#### Observed behavior:
Video ads are displayed in the game, but the game is not suspended

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@LongJiangSB, could you clarify what you mean by "the game is not suspended"? If you wish to pause your game logic before showing the rewarded video, you are in control of that. Let us know if you need anything else!

Vu Chau
MoPub Team

**Comment by LongJiangSB** [comment]
I wont use `void UnityPause(int pause);` Func,  
now i add code:
```
UnityPause(true);
[MPRewardedVideo presentRewardedVideoAdForAdUnitID:adUnitID fromViewController:aVC withReward:reward customData:@""];
```

now it's work. thanks!
