### ISSUE TITLE
MPTimer: pause function does not work properly.

### ISSUE THREAD

**Issue by sarochych** [mopub/mopub-ios-sdk#309]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.5.0
#### Device model and OS Version:
iPhone XS, iOS 13.3
#### Xcode Version:
Xcode 11.2.1
#### Ad Unit IDs used in reproducing the issue:
Irrelevant
#### Steps to reproduce the behavior:
`pause` function of the `MPTimer` doesn't save any information about seconds left before fire when pause is called. Btw, `secondsLeft` variable is calculated, but it is used only in logs.
So, when the `resume` function is called after `pause`, it just uses `timerInterval` with the value timer was initialized, so `pause` -> `resume` combination always behave the same as scheduling a new timer.
In case it is correct behavior, please, provide me with additional explanation about the idea behind this. It is pretty undesired behavior for applications with a short session.
Thanks in advance!

**Comment by chauduyphanvu** [comment]
@sarochych, thanks for letting us know! 

I see that you are using v5.5.0 of the MoPub iOS SDK. Could you try with the latest SDK release and let us know if you still see the behavior you reported? If so, could you let us know the steps or use case to reproduce that behavior? Thanks!

Vu Chau
MoPub Team

**Comment by sarochych** [comment]
@chauduyphanvu thanks for your message!

I've updated to the latest version, nothing changed.
It reproduces constantly since it is related to the `MPTimer` class design. 

Btw, below are steps to reproduce:
1. Add a banner to a view
2. call `startAutomaticallyRefreshingContents`
3. wait a half of the refresh interval
4. call `stopAutomaticallyAdRefreshing`
5. wait a few seconds
6. call  `startAutomaticallyRefreshingContents`

As a result, `startAutomaticallyRefreshingContents` method always uses initial time interval, rather than interval left before stop.
As I said, it is pretty undesired behavior for applications with a short session, since it is related to our revenue.

Looking forward for your reply!

**Comment by chauduyphanvu** [comment]
@sarochych, thanks for sharing the use case! We confirm that the behavior of using the initial time interval is by design (i.e. it works properly as intended). We do not plan to introduce the concept of pause and resume for refreshes, where the SDK would use the remaining time left in the interval.

If you would like to use a custom time interval, you can make use of `forceRefreshAd` ([API](https://github.com/mopub/mopub-ios-sdk/blob/853cbf22ef14c3f5e4aedcf6f00c944d3a2b9843/MoPubSDK/MPAdView.h#L126-L130
)) while keeping a client-side timer in your app.

Let us know if you have any questions!
