### ISSUE TITLE
accessing userAgent value causes crashing

### ISSUE THREAD

**Issue by oooosa** [mopub/mopub-ios-sdk#310]
In function `didFinishLaunchingWithOptions` I use the following code
```
NSString* agent = [MPWebBrowserUserAgentInfo userAgent];
NSLog(@"%@", agent);
```
which causes exception of EXC_BAD_ACCESS

#### MoPub SDK Version:
5.10.0
#### Device model and OS Version:
iOS 13.3 using iPhone 6s
#### Evidence:
on `NSLog(@"%@", agent);` the code stop executing. here check the screen shot
https://imgur.com/a/58UFxfx

**Comment by chauduyphanvu** [comment]
@oooosa, is there a reason for calling `[MPWebBrowserUserAgentInfo userAgent]` in your app? If you simply want to get the user agent via the MoPub SDK, you should wait until after the SDK has finished initializing before doing that.

Let us know if you have any questions!

Vu Chau
MoPub Team

**Comment by oooosa** [comment]
Hi @chauduyphanvu ,
finally someone from MoPub Team replied as I tried to call them through support as well but failed...
So on `initializeSdkWithConfiguration` application was throwing exception on  accessing `[MPWebBrowserUserAgentInfo userAgent]` value within the MoPubSDK files. 
On debugging I discovered the value of `gUserAgent` in file` MPWebBrowserUserAgentInfo.m` somehow during initialization not remains string and causes the program to throw exception. I just wanted to access the value directly to see how it changes during program execution.

Now it stop throwing exception somehow idk, but there is new exception started to pop-in on `initializeSdkWithConfiguration` call. [Stack Call Trace](https://www.codepile.net/pile/VQwpbq4v)

**Comment by chauduyphanvu** [comment]
@oooosa, thanks for the explanation! 

While I wasn't able to run your project successfully (I suspect my machine is not configured to run Cocos2d-x-generated apps), I replicated your use case in the MoPub iOS sample app but without the Exception:

<img width="1680" alt="Screen Shot 2020-01-02 at 10 32 01 AM" src="https://user-images.githubusercontent.com/25616035/71675144-28e33f00-2d4b-11ea-84c8-eb313e32537a.png">

Also, I did not see where you call `[MPWebBrowserUserAgentInfo userAgent]` in your app, so I couldn't tell if it's done at the right place/time. I recommend making that call once the MoPub SDK has finished initializing in the `completion` handle of the `initializeSdkWithConfiguration:` call.

As to why `initializeSdkWithConfiguration:` itself throws an Exception internally, could you confirm if the stack trace from that one matches the one you are seeing when you call `[MPWebBrowserUserAgentInfo userAgent]` in your app?

**Comment by oooosa** [comment]
@chauduyphanvu thanks for response, yes you are right you have not installed cocos creator that's why there are missing files and you can't build the project. I have tried to initialized the empty xcode project with MoPub SDK and it works for me as well but it does not build the exported game project from cocos creator. I have tried a very simple basic hello world game project as well and it does not work.

Please note `initializeSdkWithConfiguration` callback never called but during `initializeSdkWithConfiguration` the exception is thrown within the library file `MPURLRequest.m` at  `60: [self setValue:MPWebBrowserUserAgentInfo.userAgent forHTTPHeaderField:@"User-Agent"];` when it try to get the userAgent value.
Here is the video of exception. I  edited the file `MPWebBrowserUserAgentInfo.m` and printed the `gUserAgent` value in `userAgent` method and in `obtainUserAgentFromWebView` method to let you know it assigns correct value in `obtainUserAgentFromWebView` method but on `userAgent` method the value of `gUserAgent` no longer available.

https://easyupload.io/gmafq3

I'm trying to fix this issue for past 10 days, please help me solve the issue, you need to follow the following steps to successfully build the project of sample game project.

> 1. Download Cocos Creator 2.0.10 from here (https://cocos2d-x.org/filedown/CocosCreator_v2.0.10_mac)
> 2. Install it to Application Folder and rename the Application name to "CocosCreator_2.0.10" because that was the name of my cocos creator application when I builded this project
> 3. Open again the project in xcode. Now xcode should get the path to missing files which is present at the path (/Applications/CocosCreator_2.0.10.app/Contents/Resources/cocos2d-x/)

**Comment by chauduyphanvu** [comment]
@oooosa, thanks for the details! 

Given that this project is generated using Cocos2d-x and not Android Studio / Xcode, MoPub does not support this use case and we aren't able to debug what might have gone wrong with your project. We confirmed that initialization in an Xcode-built project works without issues. I wonder if Cocos2d-x interferes with MoPub's user agent code in any way. My recommendation is to get in touch with the team at cocos.com for additional insights and guidance.
