### ISSUE TITLE
MPViewabilityTracker - no visible interface error

### ISSUE THREAD

**Issue by saldous** [mopub/mopub-ios-sdk#314]
![Screen Shot 2020-03-24 at 12 24 03 PM](https://user-images.githubusercontent.com/3334306/77451169-b2def900-6dca-11ea-9433-5bbf198d75ca.jpg)

**Comment by dravyan** [comment]
@saldous, could you share your podfile? Have you integrated Viewability SDK as mentioned in the [documentation](http://localhost:4001/publishers/ios/viewability/#cocoapods-integration)?

Thanks,
Dravya Nataraj
MoPub Team

**Comment by saldous** [comment]
oh.. is that a new requirement? I just updated pods on a project from 3 months ago. Didn't realize you changed the requirements.

**Comment by dravyan** [comment]
@saldous, You are using Google mediation. As per their documentation, their latest adapters are compatible with MoPub SDK 5.11.0 - https://developers.google.com/admob/ios/mediation/mopub#mopub-ios-mediation-adapter-changelog.

From the screenshot, I notice that the file name is `MRController 2.m`. [MoPub SDK](https://github.com/mopub/mopub-ios-sdk) do not have such a file name or the method name `init3rdPartyViewabilityTrackers`. Please verify the integration instructions.

**Comment by saldous** [comment]
Everything was working a month ago, I just did a pods update and it broke.
