### ISSUE TITLE
5.12.0 is still using UIWebView

### ISSUE THREAD

**Issue by KAMIKAZEUA** [mopub/mopub-ios-sdk#315]
One line summary of the issue here

- [x ] I am submitting a bug report for existing functionality
- [ x] I visited https://developers.mopub.com/ and found no answer
- [ x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Download еру latest SDK https://github.com/mopub/mopub-ios-sdk/releases/download/5.12.0/mopub-framework-5.12.0.zip

**I'm using only file**: /mopub-framework-5.12.0/MoPub.xcframework/ios-armv7_arm64/**MoPub.framework**

Checked it for UIWebView
find . -type f | grep -e ".a" -e ".framework" | xargs grep -s UIWebView

#### Expected behavior:
Not using UIWebView

#### Observed behavior:
Binary file ./MoPub.xcframework/ios-armv7_arm64/MoPub.framework/MoPub **matches**

**Comment by chauduyphanvu** [comment]
@KAMIKAZEUA, thanks for letting us know! The 5.12.0 MoPub SDK framework on the release page has been updated. Let us know if you need anything else!

Vu Chau
MoPub Team
