### ISSUE TITLE
Unable to show Rewarded video

### ISSUE THREAD

**Issue by pm-preety-narvekar** [mopub/mopub-ios-sdk#321]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

Integration of rewarded video is done as per the iOS guide by MoPub.
```
// Loaded Rewarded video 
[MPRewardedVideo loadRewardedVideoAdWithAdUnitID:<Ad_Unit> withMediationSettings:@[]];
[MPRewardedVideo setDelegate:self forAdUnitId:<Ad_Unit>];
```
On receiving success callback in ```rewardedVideoAdDidLoadForAdUnitID```, shown rewarded video as:
```
BOOL isAvailable = [MPRewardedVideo hasAdAvailableForAdUnitID:<Ad_Unit>];
    
    if (isAvailable) {
        MPRewardedVideoReward *reward = [[MPRewardedVideoReward alloc] initWithCurrencyType:@"Coins" amount:@5];
        [MPRewardedVideo presentRewardedVideoAdForAdUnitID:<Ad_Unit>
                                        fromViewController:self
                                                withReward:reward
                                                customData:<Publisher_id_from_portal>];
    }
```
The given test ad unit has reward set with currency type as "Coins" and amount as 5. The same is also received in response. But in class ```MPRewardedVideoAdManager``` of MoPub SDK, in method ```presentRewardedVideoAdFromViewController```, it fails to find the reward set from application in the rewards received from server at line:
```if (![self.availableRewards containsObject:reward])``` and throws error.

#### MoPub SDK Version:
5.12.1

#### Device model and OS Version:
Simulator iPhone 8, iOS 11.3

#### Xcode Version:
Xcode 11.0

#### Ad Unit IDs used in reproducing the issue:
635009bb38be4b78883381a6915d3801

#### Steps to reproduce the behavior:
1. Load rewarded video
2. Try to show after receiving callback ```rewardedVideoAdDidLoadForAdUnitID```

#### Expected behavior:
Rewarded Video should be shown.

#### Evidence:
Rewards received from server and the reward set through application are are printed as (XCode logs) at the same line in ```MPRewardedVideoAdManager```:
```
(lldb) po self.availableRewards
<__NSArrayM 0x604000442670>(
5 Coins
)
(lldb) po reward
5 Coins
(lldb) 
```

**Comment by dravyan** [comment]
@pm-preety-narvekar, thank you for your question. The reward for an adunit is set on the MoPub UI and the SDK will fetch the available rewards from our server at `availableRewardsForAdUnitID`. It is recommended to set the reward on the MoPub UI as suggested in our [documentation](https://developers.mopub.com/publishers/ios/rewarded-video/#step-5-show-the-rewarded-video).

Thanks,
MoPub Team
