### ISSUE TITLE
IOS UIWebView policy

### ISSUE THREAD

**Issue by avalon451990** [mopub/mopub-ios-sdk#322]
Using version 5.11.0,but refused by apple store for UIWebView policy!

Found that version 5.9.0 have resolved!!

**Comment by chauduyphanvu** [comment]
@avalon451990, the UIWebView issue has been completely addressed in the 5.13.0 SDK release, where we removed the Moat and IAS viewability SDKs. Feel free to upgrade to that version to get this fix!

Vu Chau
MoPub Team
