### ISSUE TITLE
Info.plist in MoPubSDK folder cause build time error in Xcode.

### ISSUE THREAD

**Issue by sgabello** [mopub/mopub-ios-sdk#323]
At build time, Xcode copies all the files for a target in the same directory. Hence you cannot have files with the same name in different folders for the same target. `Info.plist` is already the default project plist file. Another copy cannot be added to the project. It should be removed from the repository, given a different name, or the documentation should contain instructions on what to do with it in case of manual integration of the SDK.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
- Add MoPubSDK folder to the project
- Build the project
#### Expected behavior:
- Project builds correctly

#### Observed behavior:
- Build-time error is raised

#### Evidence:
Multiple commands produce '/Users/andrea/Library/Developer/Xcode/DerivedData/iTorch-ccnkpmzorleisfdbybohvyviyzyo/Build/Products/Debug-iphoneos/iTorch.app/Info.plist':
1) Target 'iTorch' (project 'iTorch') has copy command from '/Users/andrea/git/Pixelinlove/iTorch/iTorch/Utilities/MoPubSDK/Info.plist' to '/Users/andrea/Library/Developer/Xcode/DerivedData/iTorch-ccnkpmzorleisfdbybohvyviyzyo/Build/Products/Debug-iphoneos/iTorch.app/Info.plist'
2) Target 'iTorch' (project 'iTorch') has process command with output '/Users/andrea/Library/Developer/Xcode/DerivedData/iTorch-ccnkpmzorleisfdbybohvyviyzyo/Build/Products/Debug-iphoneos/iTorch.app/Info.plist'

**Comment by dravyan** [comment]
@sgabello, thank you for reporting. You can delete the `info.plist` from the MoPubSDK folder if you are integrating via source if it is causing any build issues for you. That should resolve the issue.

Thanks,
MoPub Team

**Comment by sgabello** [comment]
@dravyan thanks! Will do.

**Comment by chauduyphanvu** [comment]
This issue has been resolved in v5.14.0. Let us know if you continue seeing the issue!
