### ISSUE TITLE
a bug in iOS SDK

### ISSUE THREAD

**Issue by dinghub** [mopub/mopub-ios-sdk#324]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality

iOS SDK
code in file MPImageLoader.m, 
function 
- (void)loadImageForURL:(NSURL *)imageURL intoImageView:(UIImageView *)imageView
line 42:
isAdViewInHierarchy = [self.delegate nativeAdViewInViewHierarchy];

the delegate is a weak property, this line has big chance to fail, because it's running in block, the delegate will be nil.

**Comment by dravyan** [comment]
@dinghub, thank you for reaching out. The delegates should be weak to prevent retain cycles. This is intended and by design. if delegate becomes nil then the method call will just silently fail and continue. Are you noticing any crash or error?. If yes, can you share logs and steps to replicate?

Thanks,
MoPub Team

**Comment by dinghub** [comment]
Thank you for the reply.
the weak declaration of the delegate is ok, but inside the block, you should retain it, similar as strong_self. Otherwise, isAdViewInHierarchy will be always false.
This issue should be related issue #266 
https://github.com/mopub/mopub-ios-sdk/issues/266

since FVivolo provided codes to reproduce the problem in #266, I will not prepare the code again. Please let me know if you still need the reproducing codes.

**Comment by dravyan** [comment]
@dinghub, do you still need help on this issue?. This design decision is to handle the issues retain cycles. if you have made any changes in your project and can share it to test it out, let us know.
