### ISSUE TITLE
Periodic audio polling interfering with app audio

### ISSUE THREAD

**Issue by lukevanin** [mopub/mopub-ios-sdk#329]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
```
% cat Podfile.lock | grep mopub
    - mopub-ios-sdk (~> 5.5)
    - mopub-ios-sdk/Core (~> 5.8)
    - mopub-ios-sdk/NativeAds (~> 5.8)
    - mopub-ios-sdk/Core (~> 5.8)
    - mopub-ios-sdk/NativeAds (~> 5.8)
    - mopub-ios-sdk/Core (~> 5.8)
    - mopub-ios-sdk/Core (~> 5.8)
    - mopub-ios-sdk/Core (~> 5.6)
    - mopub-ios-sdk/NativeAds (~> 5.6)
    - mopub-ios-sdk/Core (~> 5.6)
    - mopub-ios-sdk/NativeAds (~> 5.6)
  - mopub-ios-sdk (5.12.1):
    - mopub-ios-sdk/MoPubSDK (= 5.12.1)
  - mopub-ios-sdk/Avid (5.12.1):
    - mopub-ios-sdk/Core
  - mopub-ios-sdk/Core (5.12.1)
  - mopub-ios-sdk/Moat (5.12.1):
    - mopub-ios-sdk/Core
  - mopub-ios-sdk/MoPubSDK (5.12.1):
    - mopub-ios-sdk/Avid
    - mopub-ios-sdk/Core
    - mopub-ios-sdk/Moat
    - mopub-ios-sdk/NativeAds
  - mopub-ios-sdk/NativeAds (5.12.1):
    - mopub-ios-sdk/Core
    - mopub-ios-sdk
    - mopub-ios-sdk
    - mopub-ios-sdk
    - mopub-ios-sdk (>= 5.12.1)
  - "AppMonet_Mopub-universal (from `{:http=>\"https://androidsdk%40appmonet:8524be7aa419b4f729863dcf81fdd339b47862eb@appmonet.bintray.com/MonetBidder/com/monet/ios/appmonet-mopub/1.6.4/appmonet-mopub-universal.zip\"}`)"
  - mopub-ios-sdk (~> 5.12.0)
    - mopub-ios-sdk
    :http: "https://androidsdk%40appmonet:8524be7aa419b4f729863dcf81fdd339b47862eb@appmonet.bintray.com/MonetBidder/com/monet/ios/appmonet-mopub/1.6.4/appmonet-mopub-universal.zip"
    :http: "https://androidsdk%40appmonet:8524be7aa419b4f729863dcf81fdd339b47862eb@appmonet.bintray.com/MonetBidder/com/monet/ios/appmonet-mopub/1.6.4/appmonet-mopub-universal.zip"
  mopub-ios-sdk: d1640225b34ad74700e2acddb116cac634fc45d8
```

#### Device model and OS Version:
iPhoneX iOS 13.5.1

#### Xcode Version:
Xcode 11.5

#### Ad Unit IDs used in reproducing the issue:
N/A

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

1. Enable Mopub SDK, e.g.
```
MoPub.sharedInstance().initializeSdk(with: configuration, completion: {})
```
2. Turn device volume up to maximum level, or use headphones. Turn off the hardware mute switch (unmute audio).
3. A hissing sound can be heard to occur about once every second.
4. Enter text into an input field (ie tap on a text field and type on the keyboard).

#### Expected behavior:
Sounds (keyboard, video, etc) should play normally in the application.

#### Observed behavior:
1. The app emits a loud hissing sound about once every second.
2. When typing on the keyboard some keypresses are extremely loud while others are at the expected level level.

#### Evidence:
Behaviour appears to be due to `MPUBMoatVideoUtil getSystemVolume` polling the audio volume. 

See attached screenshot from instruments:
<img width="883" alt="Screenshot 2020-07-14 at 11 43 58" src="https://user-images.githubusercontent.com/550579/88380940-bfd61e00-cda5-11ea-9a1b-f525312502e9.png">

**Comment by chauduyphanvu** [comment]
@lukevanin, the caller (`MPUBMoatBridge`) is the Moat SDK and not MoPub. Moreover, we no longer bundle Moat in [v5.13.0](https://github.com/mopub/mopub-ios-sdk/blob/master/CHANGELOG.md#version-5130-june-15-2020). 

I see that you are using v5.12.1. Please upgrade to 5.13.0 to resolve this issue. Thank you!

Vu Chau
MoPub Team
