### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException initWithAdProperties

### ISSUE THREAD

**Issue by mmdock** [mopub/mopub-ios-sdk#331]
One line summary of the issue here
Top crash of my app is from MoPub, and it has been growing the last few weeks.
- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
From my Podfile:
    pod 'MoPub-FacebookAudienceNetwork-Adapters', '5.8.0.0'
    pod 'MoPub-AdMob-Adapters', '7.57.0.0'

From my Podfile.lock:
  - MoPub-AdMob-Adapters (7.57.0.0):
    - MoPub-AdMob-Adapters/MoPub (= 7.57.0.0)
    - MoPub-AdMob-Adapters/Network (= 7.57.0.0)
  - MoPub-AdMob-Adapters/MoPub (7.57.0.0):
    - mopub-ios-sdk/Core (~> 5.8)
    - mopub-ios-sdk/NativeAds (~> 5.8)
  - MoPub-AdMob-Adapters/Network (7.57.0.0):
    - Google-Mobile-Ads-SDK (= 7.57.0)
    - mopub-ios-sdk/Core (~> 5.8)
    - mopub-ios-sdk/NativeAds (~> 5.8)
  - MoPub-FacebookAudienceNetwork-Adapters (5.8.0.0):
    - MoPub-FacebookAudienceNetwork-Adapters/MoPub (= 5.8.0.0)
    - MoPub-FacebookAudienceNetwork-Adapters/Network (= 5.8.0.0)
  - MoPub-FacebookAudienceNetwork-Adapters/MoPub (5.8.0.0):
    - mopub-ios-sdk/Core (~> 5.6)
    - mopub-ios-sdk/NativeAds (~> 5.6)
  - MoPub-FacebookAudienceNetwork-Adapters/Network (5.8.0.0):
    - FBAudienceNetwork (= 5.8.0)
    - mopub-ios-sdk/Core (~> 5.6)
    - mopub-ios-sdk/NativeAds (~> 5.6)
  - mopub-ios-sdk/Core (5.12.1)
  - mopub-ios-sdk/NativeAds (5.12.1):
    - mopub-ios-sdk/Core

#### Device model and OS Version:
<img width="380" alt="Screen Shot 2020-07-31 at 10 37 13 AM" src="https://user-images.githubusercontent.com/2423465/89061596-d9351800-d319-11ea-8af6-6c17d8f3578e.png">
<img width="286" alt="Screen Shot 2020-07-31 at 10 37 48 AM" src="https://user-images.githubusercontent.com/2423465/89061630-e9e58e00-d319-11ea-9e79-76482f59120b.png">

#### Xcode Version:
11.6

#### Ad Unit IDs used in reproducing the issue:
Unknown.

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
Unknown
#### Expected behavior:
As concisely as possible, describe the expected behavior.
No crash

#### Observed behavior:
As concisely as possible, describe the observed behavior.
Users are experiencing a crash as they attempt to load ads
There has been a spike in this issue relatively recently: 
<img width="850" alt="Screen Shot 2020-07-31 at 10 41 28 AM" src="https://user-images.githubusercontent.com/2423465/89061962-7c862d00-d31a-11ea-982e-77d6045c3d1a.png">

#### Evidence:
Device log files, Network log file, etc.
Fatal Exception: NSInvalidArgumentException
-[NSNull length]: unrecognized selector sent to instance 0x1c918bc30
-[MPMoPubNativeAdAdapter initWithAdProperties:]

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x18c2a6a48 __exceptionPreprocess
1  libobjc.A.dylib                0x18bfcdfa4 objc_exception_throw
2  CoreFoundation                 0x18c1aa5a8 -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x18c2aaaf4 ___forwarding___
4  CoreFoundation                 0x18c2aca7c _CF_forwarding_prep_0
5  CoreFoundation                 0x18c26c008 _CFURLCreateWithURLString
6  Foundation                     0x18c564b24 +[NSURL(NSURL) URLWithString:relativeToURL:]
7  MoPub                          0x10616a298 -[MPMoPubNativeAdAdapter initWithAdProperties:] + 76 (MPMoPubNativeAdAdapter.m:76)
8  MoPub                          0x10616ad70 -[MPMoPubNativeCustomEvent requestAdWithCustomEventInfo:adMarkup:] + 24 (MPMoPubNativeCustomEvent.m:24)
9  MoPub                          0x106172fa4 -[MPNativeAdRequest getAdWithConfiguration:] + 224 (MPNativeAdRequest.m:224)
10 MoPub                          0x106173a20 -[MPNativeAdRequest fetchAdWithConfiguration:] + 285 (MPNativeAdRequest.m:285)
11 MoPub                          0x106174274 -[MPNativeAdRequest nativeCustomEvent:didFailToLoadAdWithError:] + 354 (MPNativeAdRequest.m:354)
12 Her                            0x105199f8c -[FacebookNativeCustomEvent nativeAd:didFailWithError:] + 106 (FacebookNativeCustomEvent.m:106)
13 Her                            0x105299a94 -[FBNativeAd nativeAdBase:didFailWithError:] + 224 (FBNativeAd.m:224)
14 Her                            0x10529dc24 -[FBNativeAdBase tellDelegateThatWeDidFailWithError:] + 884 (FBNativeAdBase.m:884)
15 Her                            0x10529b4a4 -[FBNativeAdBase displayAdController:didFailWithError:] + 447 (FBNativeAdBase.m:447)
16 libdispatch.dylib              0x18bf72610 _dispatch_call_block_and_release
17 libdispatch.dylib              0x18bf73184 _dispatch_client_callout
18 libdispatch.dylib              0x18bf25190 _dispatch_main_queue_callback_4CF$VARIANT$mp
19 CoreFoundation                 0x18c2245e4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
20 CoreFoundation                 0x18c21f5d8 __CFRunLoopRun
21 CoreFoundation                 0x18c21eadc CFRunLoopRunSpecific
22 GraphicsServices               0x1961bf328 GSEventRunModal
23 UIKitCore                      0x19032c63c UIApplicationMain
24 Her                            0x1046a1008 main + 11 (main.swift:11)
25 libdyld.dylib                  0x18c0a8360 start

**Comment by dravyan** [comment]
@mmdock, this issue has been resolved in the latest MoPub SDK release [5.13.x](https://github.com/mopub/mopub-ios-sdk/releases). We recommend updating to the latest SDK 5.13.1. Let us know how it goes.

Thanks,
MoPub Team
