### ISSUE TITLE
Unify proper AudioSession handling for mopub and adapters for (native) ads

### ISSUE THREAD

**Issue by heyarny** [mopub/mopub-ios-sdk#334]
We're having an App with Audio Playback features and use native ads inside our feeds.

Now we noticed our audio just stops and resumes as some muted video ad appears or disappears.
This ruins the user experience of our app.

There are ways to implement delegates from admob/facebook frameworks, but they're very different and even makes it impossible to implement them without breaking the whole mopub infrastructure.

// Admob examle; easy
[[GADMobileAds sharedInstance] audioVideoManager].audioSessionIsApplicationManaged = YES;
[[GADMobileAds sharedInstance] audioVideoManager].delegate = self;

// audience network; impossible to implement with mopub
https://developers.facebook.com/docs/audience-network/guides/audio/ios

I'm not aware of other ad frameworks or even mopub itself and don't seem to find a solution as of now.

**Comment by p158276** [comment]
Hi @heyarny ,
Thanks for reaching out. 
May I know what audio library are you using in your project?

Yoyo Lin,
MoPub Support Team

**Comment by heyarny** [comment]
@p158276 
I'm using the native AudioQueue/CoreAudio of iOS.

MoPub SDK Version: 5.13.1
Device model and OS Version: iPhoneXs, iOS 13.5.1
Xcode Version: 11.6
Ad Unit IDs used in reproducing the issue: Use the native video unit ids
Steps to reproduce the behavior:
1. Play some background audio in your app.
2. Let the video ad appear (scroll to it or switch to the view with the native ad)

Expected behavior:
Background sound should not be interrupted, unless user taps the unmute icon on the ad.

Observed behavior:
Mopub framework is missing of audio session delegates which each ad framework is providing.
One has to know when to stop or resume background sound.

See the provided links to the ad SDKs:
https://developers.google.com/admob/ios/api/reference/Classes/GADAudioVideoManager
https://developers.facebook.com/docs/audience-network/guides/audio/ios

There is nothing the like at Mopub (native ads).

**Comment by p158276** [comment]
Hi @heyarny,
Thanks for letting us know. We currently don't have the audio session delegates. I'll circle back to the internal team and let you know if there's any update.

For the background sound interrupt behaviour:
I tried to test AVAudioSession/AVAudioPlayer with the native ad and the music won't be interrupted when ad shows. Can you try the combination above and see if it works for you?

Thanks.

Yoyo Lin,
MoPub Support Team

**Comment by heyarny** [comment]
@p158276 
It happens with native ads from admob and facebook.

I haven't tested it with mopub marketplace, as I never get any inventory there (been trying to contact support several times, without any response and gave up on that) and there is no ad unit id for native videos ads.
So no idea about mopub itself.

**Comment by p158276** [comment]
Hi @heyarny ,
I've tested with Admob and Facebook native video. Both worked fine by using AVAudioSession/AVAudioPlayer and the music won't be interrupted when ad shows. 

Can you try the combination above and see if it works for you? If not, feel free to send us the project or try to reproduce the same problem in our [Sample app](https://github.com/mopub/mopub-ios-sdk/tree/master/Canary). Our team will help to investigate on it.

For no inventory problem, you can try to connect to [support portal](https://developers.mopub.com/support/) and file a ticket to apply for the marketplace.

 Thanks.

Yoyo Lin,
MoPub Support Team

**Comment by heyarny** [comment]
@p158276 what AVAudioSession category are you using?
I'm using AVAudioSessionCategoryPlayback.

**Comment by p158276** [comment]
I'm using AVAudioSessionCategoryPlayback too.

Here is my code snippet in our Sample app project.

```
let url = Bundle.main.url(forResource: "example", withExtension: "mp3")

do {
   try AVAudioSession.sharedInstance().setCategory(.playback, mode: .default)
   try AVAudioSession.sharedInstance().setActive(true)

   player = try AVAudioPlayer(contentsOf: url!, fileTypeHint: AVFileType.mp3.rawValue)
   player?.play()

} catch let error {
   print(error.localizedDescription)
}
```
