### ISSUE TITLE
Third party AdNetwork returned through mediation requests cannot be resolved

### ISSUE THREAD

**Issue by Baoyin-Sun** [mopub/mopub-ios-sdk#335]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version: 
5.13.1
#### Device model and OS Version: 
iPhone 7，iOS13
#### Xcode Version:
Xcode11.6
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

MPMoPubConfiguration * sdkConfig = [[MPMoPubConfiguration alloc] initWithAdUnitIdForAppInitialization:xxxx];
    sdkConfig.loggingLevel = MPBLogLevelDebug;
    sdkConfig.additionalNetworks = @[GoogleAdMobAdapterConfiguration.class];

    [[MoPub sharedInstance] initializeSdkWithConfiguration:sdkConfig completion:^{
    }];

 MPStaticNativeAdRendererSettings *settings = [[MPStaticNativeAdRendererSettings alloc] init];
                settings.renderingViewClass = [xxx class];
                MPNativeAdRendererConfiguration *config = [MPStaticNativeAdRenderer rendererConfigurationWithRendererSettings:settings];
                
                MPStaticNativeAdRendererSettings *admobSettings = [[MPStaticNativeAdRendererSettings alloc] init];
                admobSettings.renderingViewClass = [xxx class];
                MPNativeAdRendererConfiguration *googleConfiguration = [MPGoogleAdMobNativeRenderer rendererConfigurationWithRendererSettings:admobSettings];
 
                NSArray *configurations = @[config, googleConfiguration];

NSDictionary *localExtras = @{@"testDevices" : @"xxx"};
                    MPNativeAdRequestTargeting *targeting = [MPNativeAdRequestTargeting targeting];
                    targeting.localExtras = localExtras;
                    self.adMopubNaticeRequest.targeting = targeting;
[self.adMopubNaticeRequest startWithCompletionHandler:^(MPNativeAdRequest *request, MPNativeAd *response, NSError *error) {
}];

#### Expected behavior:
As concisely as possible, describe the expected behavior.

Returns the Third party Network 

#### Observed behavior:
As concisely as possible, describe the observed behavior.

[MoPub][MPAdServerCommunicator] (30) Failed to parse ad response into JSON: The data couldn’t be read because it isn’t in the correct format.

[MoPub][MPNativeAdRequest] Error: Couldn't retrieve an ad from MoPub. Message: Error Domain=com.mopub.iossdk Code=30 "Failed to parse ad response into JSON: The data couldn’t be read because it isn’t in the correct format." UserInfo={NSLocalizedDescription=Failed to parse ad response into JSON: The data couldn’t be read because it isn’t in the correct format.}

#### Evidence:
Device log files, Network log file, etc.
![截屏2020-08-25 上午10 17 10](https://user-images.githubusercontent.com/16753034/91115164-31163300-e6bc-11ea-8077-2f833f8da886.png)

**Comment by chauduyphanvu** [comment]
@Baoyin-Sun, thanks for letting us know! Would you be able to share the ad unit ID you used to reproduce that error? If not, is it possible to share some console/device logs with us (make sure you have the debug log level for extra verbosity). Thanks!

Vu Chau
MoPub Team

**Comment by Baoyin-Sun** [comment]
> @Baoyin-Sun, thanks for letting us know! Would you be able to share the ad unit ID you used to reproduce that error? If not, is it possible to share some console/device logs with us (make sure you have the debug log level for extra verbosity). Thanks!
> 
> Vu Chau
> MoPub Team

@chauduyphanvu, unit ID : c6f66411472547099792700f5c407e75, 
[Mopub Log.txt](https://github.com/mopub/mopub-ios-sdk/files/5127846/Mopub.Log.txt)
