### ISSUE TITLE
Repo has broken link for additional documentation

### ISSUE THREAD

**Issue by xta** [mopub/mopub-ios-sdk#337]
Repo readme links to "https://www.mopub.com/en/resources/docs" which is not a valid page.

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

The readme says "Additional documentation can be found here.". The link goes to https://www.mopub.com/en/resources/docs which is 404.

**Comment by chauduyphanvu** [comment]
Thanks for letting us know! That's an old URL, and we'll remove it from the README.

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
This has been fixed in [v5.14.0](https://github.com/mopub/mopub-android-sdk/commit/e8b8d865535855dacd65fdf741e1c0d5b7797ca5).
