### ISSUE TITLE
Companion ad not showing

### ISSUE THREAD

**Issue by LucileBillard** [mopub/mopub-ios-sdk#338]
On the 5.13.1 mopub **sample app** (sdk 5.13.1) the companion ad image does not show (But it works fine when using an old version the of sample app with **sdk 5.7.1** )

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:

Just test this ad unit in the sample app

#### Expected behavior:
Should display the companion ad image at the end of the premium video.

#### Observed behavior:
We see this:
![IMG_0043](https://user-images.githubusercontent.com/5479803/91971659-da42d600-ed19-11ea-938d-f9b63ce47ff2.PNG)

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@LucileBillard, I tested your ad unit ID in our 5.13.1 sample app but did not reproduce this issue. It seems to be creative-specific (and the one creative I kept getting did not exhibit this issue).

If you can reproduce this issue yourself, would you be able to share with us the console logs? Make sure you [enable debug logging](https://developers.mopub.com/publishers/ios/test/#enable-logging) so the SDK will print the ad response. Either that or a [Charles](https://www.charlesproxy.com/) log will help us identify the creative and debug this issue. Thanks!

Vu Chau
MoPub Team

**Comment by LucileBillard** [comment]
@chauduyphanvu Thank you for the feedback. 
Here is a test adunit to reproduce the bug (in the sample app 5.13.1): **75a614db148e4e57a516b3743d5b6eaa** with the following vast:
`<VAST version="3.0">
  <Ad id="static">
    <InLine>
      <AdSystem>Static VAST Template</AdSystem>
      <AdTitle>Gifi </AdTitle>
      <Impression></Impression>
	  <Extensions>	    
		<Extension type="MoPub">
			<MoPubForceOrientation>device</MoPubForceOrientation>
			<MoPubCtaText>RENTREE</MoPubCtaText>
		</Extension>
	  </Extensions>
      <Creatives>
        <Creative>
			<CompanionAds>
				<Companion width="1080" height="1920">
					<StaticResource creativeType="image/jpeg">
						<![CDATA[https://i.picsum.photos/id/623/200/300.jpg?hmac=2LlPuWimnDeGk-zZPKKgRVozFd3c-26BinXWcxfTtXo]]>
					</StaticResource>
					<CompanionClickThrough>
						<![CDATA[mopubnativebrowser://navigate?url=https%3A%2F%2Fcatalogue.gifi.fr%2FFR-s35-v01-2020%2Findex.html%23page%2F1%3Futm_source%3Dbravoloto%26utm_medium%3Dinterstitiel%26utm_campaign%3Dcata-s35%26utm_content%3D%26utm_term%3D]]>
					</CompanionClickThrough>
				</Companion>
			</CompanionAds>		
          <Linear>
            <Duration>00:00:15</Duration>
            <TrackingEvents>
              <Tracking event="start">http://example.com/pixel.gif</Tracking>
              <Tracking event="complete">http://example.com/pixel.gif</Tracking>
            </TrackingEvents>
            <VideoClicks>
              <ClickThrough>
		<![CDATA[mopubnativebrowser://navigate?url=https%3A%2F%2Fcatalogue.gifi.fr%2FFR-s35-v01-2020%2Findex.html%23page%2F1%3Futm_source%3Dbravoloto%26utm_medium%3Dinterstitiel%26utm_campaign%3Dcata-s35%26utm_content%3D%26utm_term%3D]]>
		</ClickThrough>
              <ClickTracking>http://example.com/pixel.gif</ClickTracking>
            </VideoClicks>
            <MediaFiles>
              <MediaFile type="video/mp4" bitrate="7" width="360" height="640">
                <![CDATA[https://content.jwplatform.com/videos/AEhg3fFb-bPwArWA4.mp4]]>
              </MediaFile>
            </MediaFiles>
           </Linear>
        </Creative>
      </Creatives>
    </InLine>
  </Ad>
</VAST>`

Some logs when the bug occurs in our app (with some urls removed): 
[mopublogs.txt](https://github.com/mopub/mopub-ios-sdk/files/5169870/mopublogs.txt)

**Comment by chauduyphanvu** [comment]
Thank you for the VAST response. I saw the issue you described, and will check with the rest of the team on it. Stay tuned!

**Comment by chauduyphanvu** [comment]
@LucileBillard, looking through the VAST some more, this is a creative-related issue. The VAST XML structure around `<CompanionAds>` is not following the specs. Each companion ad is supposed to be wrapped in a separate `<Creative>` tag. Companion ads shouldn't be sharing the same `<Creative>` tag with a `<Linear>` ad.

I have corrected it and you can see the change in this diff: https://www.diffchecker.com/FUGvmifB.

If a companion ad is malformed, the SDK will blur the last frame of the video, which is what's happening here. It's not a bug.
