### ISSUE TITLE
Issue with MPCollectionViewAdPlacer on iOS 14

### ISSUE THREAD

**Issue by ndhieuvn212** [mopub/mopub-ios-sdk#341]
I create a custom  ArticleCollectionView: UICollectionView and add an MPCollectionViewAdPlacer

```
final class ArticleCollectionView: UICollectionView {
var placer: MPCollectionViewAdPlacer?

func configureAdPlacer(mopubIdentifier: String) {
    let rendererConfigurations = self.rendererConfigurations()
    let targeting = MPNativeAdRequestTargeting()
    
    self.placer = MPCollectionViewAdPlacer(collectionView: self, viewController: self.rootViewController, rendererConfigurations: rendererConfigurations)
    
    targeting?.desiredAssets = MoPub.allAssets
    self.placer?.loadAds(forAdUnitID: mopubIdentifier, targeting: targeting)
    self.placer?.delegate = self
  }
...
}
```

This works properly on iOS 10, 12, 13, But It can not work on iOS 14.

On iOS 14, when the UICollectionView scroll, it calls many time on this method forwardingTargetForSelector  then crash.

-[MPCollectionViewAdPlacer forwardingTargetForSelector:] at /Pods/mopub-ios-sdk/MoPubSDK/NativeAds/MPCollectionViewAdPlacer.m:356

MoPub SDK Version:

5.13.1
Device model and OS Version:

iPhone XR (14.0)
Xcode Version:

12.0 Beta 4 & 11.6

#### Ad Unit IDs used in reproducing the issue:
161c8bde96764eaaa08cc2f06d6244b50

#### Steps to reproduce the behavior:
scroll the UICollectionView then see the crash.

#### Expected behavior:
When scoll UIcollectionView, it should scroll normally then ads will appear on the cell

#### Observed behavior:
When start to scroll on iOS 14, It hangs for long time then show crashes

#### Evidence:
[Image 1](https://prnt.sc/uitdnp)
[Image 2](https://prnt.sc/uiteyz)

aSelector is always  (SEL) aSelector = "_diffableDataSourceImpl"

on iOS 13 is does not have this

Thanks

**Comment by p158276** [comment]
Hi @ndhieuvn212 ,
Thanks for reaching out. I tried to reproduce the same by implementing the code snippet you provided above. But I didn't encounter the same crash as you reported. Do you mind sharing the project with us which can reflect the same problem?

Yoyo Lin
MoPub Team

**Comment by ndhieuvn212** [comment]
Hi Yoyo Lin,
I can not share my project, but I can make a demo with same workflow with the same crash. I will share you soon.
Thanks,

**Comment by p158276** [comment]
Hi @ndhieuvn212 ,
Sure. Please share the file here. Thanks!

**Comment by ndhieuvn212** [comment]
Hi @p158276 
Here is the sample code that can see the issue.
It can run well on iOS bellow 14.
on iOS 14, we can not scroll, it will cause the crash.
[Sourde Code](https://www.dropbox.com/s/5m7ldtu69xhr94r/testMopub.zip?dl=0)

**Comment by p158276** [comment]
Hi @ndhieuvn212 ,
Thanks for sharing the code.
I'll bring back to our internal team and comment here when we have any updates.

**Comment by p158276** [comment]
Hi @ndhieuvn212,
Thanks for waiting. I've compared your project with our sample App (Native Collection). 
When I set the `forwardingTargetForSelector` as a breakpoint in our sample App, I didn't see that line was triggered. 
This generally happened when receives a message it cannot handle. It seems no ad renderer was registered in your project too. I would suggest you can also try to reproduce the same error in our sample App if you can. 

From the project you provided, I am seeing you are trying to show the banner ad in the Native Ads Ad Placer. As AdPlacer is for non-advanced table setups, it is recommended you should use Manual integration for this advanced setup.

Yoyo Lin
MoPub Team

**Comment by ndhieuvn212** [comment]
This case crash is that: When create a custom UICollectionView then add it to UIViewcontroller. If we implement it directly in the UICollectionView into UIVIewcontroller, it will work well.
In my case, I have many place to reuse my Custom UICollectionView so it will crash.

Would you please check that case?
