### ISSUE TITLE
No Module Found when Installing Via Cocoapods

### ISSUE THREAD

**Issue by willswinson** [mopub/mopub-ios-sdk#343]
One line summary of the issue here

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### Ad Unit IDs used in reproducing the issue:
Cant build the project.

#### Steps to reproduce the behavior:
Install via CocoaPods

```
pod 'mopub-ios-sdk'

target 'SomeApp' do
  pod 'SWXMLHash', '~> 5.0.1'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
# pod 'Firebase/AdMob'
  pod 'Alamofire', '4.8.2'
  pod 'AlamofireImage', '~> 3.5'
  pod 'KeychainAccess'
  pod 'mopub-ios-sdk'
end
```

#### Expected behavior:
Can import MoPubSDK

#### Observed behavior:
No module found 'MoPubSDK'

All other cocoapods are fine except MoPubSDK, which it can't find, so cocoapods is fine.

#### Evidence:
Don't have much. It just doesn't recognize it.

Tried to delete derive data.
Tried to clean
Tried to delete all cocoapod files and folders and reinstall.
Tried pod deintegrate -> pod install -> pod update
Tried updating cocoapods
Framework paths are fine in build settings

**Comment by chauduyphanvu** [comment]
@willswinson, do you still see that error when installing for another Xcode project? If so, do you have the full error messages from CocoaPods? What happens if you run `pod install --repo-update` instead of `pod update`?

If you still see errors with a fresh project, share it with us and we will take a look.

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
Closing as irreproducible.
