### ISSUE TITLE
Demo Native Video URL can not play

### ISSUE THREAD

**Issue by caiqingminjson** [mopub/mopub-ios-sdk#344]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Ad Unit IDs used in reproducing the issue:
b2b67c2a8c0944eda272ed8e4ddf7ed4
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@caiqingminjson, we have deprecated the support for native video earlier this month. All native video demand sources have stopped serving, and it is recommended for you to remove native video code from your app.

We will discuss following up with a detailed guide on actions required of publishers to stay compatible with the deprecation of native video.

Let us know if you have any questions!

Vu Chau
MoPub Team
