### ISSUE TITLE
No such module 'MoPub' error

### ISSUE THREAD

**Issue by polmum** [mopub/mopub-ios-sdk#347]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
Any version.

#### Device model and OS Version:
Compile issue.

#### Xcode Version:
Any versoin.

#### Steps to reproduce the behavior:
I'm adding a sample project, but basically you have to include MoPub via cocoapods, without using `use_frameworks` or `modular_headers`.

#### Expected behavior:
I expected to be able to import and use MoPub classes from Swift code.

#### Observed behavior:
When importing, getting an error `No such module 'MoPub'.

#### Evidence:
Sample project:
[MoPubTest.zip](https://github.com/mopub/mopub-ios-sdk/files/5433050/MoPubTest.zip)
Unzip, run `pod install` from root, open workspace and run.

This pull request #297 fixes the issue. I know that using `use_frameworks` or `modular_headers` is a workaround, but I believe that the PR has the correct solution.

**Comment by p158276** [comment]
Hi @polmum ,
Thanks for your feedback. I will check this question with our team and get back to you when there's any update.

Yoyo Lin
MoPub Team

**Comment by p158276** [comment]
Hi @polmum ,
We'll fix this issue in the following SDK release. Thanks for raising this up.

Yoyo Lin 
MoPub Team

**Comment by polmum** [comment]
Hi!
That's great! Thanks

**Comment by p158276** [comment]
Hi @polmum - This has been addressed in the [5.15.0](https://github.com/mopub/mopub-ios-sdk/releases/tag/5.15.0) release. Thank you again for your report.
