### ISSUE TITLE
Adding registerAppForAdNetworkAttribution

### ISSUE THREAD

**Issue by zedwill** [mopub/mopub-ios-sdk#348]
I have noticed the **Mopub iOS Sample App** does not include the **SKAdNetwork** registration call.

Calling _registerAppForAdNetworkAttribution_() on app open will enable all mopub DSPs to test their **SKAdNetwork** integration without the need of a real app, complementing the Mopub **SKAdNetwork** documentation found [here](https://developers.mopub.com/dsps/integration/ios14proposal/).

According to [Apple documentation](https://developer.apple.com/documentation/storekit/skadnetwork/2943654-registerappforadnetworkattributi) the method is safe to be called repeatedly, so it can be safely called multiple times and there is no need of limiting the call to once at first aperture. Hence the change would be a one liner.

**Comment by p158276** [comment]
Hi @zedwill ,
Thanks for your feedback. I will check this question with our team and get back to you when there's any update.
Meanwhile, do you want to test advertising campaigns targeting by using sample app?

Yoyo Lin
MoPub Team

**Comment by chauduyphanvu** [comment]
This has been addressed in v5.15.0 (https://github.com/mopub/mopub-ios-sdk/blob/043faa10a07d7d8010427ef2e1a59e4fb77177be/Canary/Canary/SceneDelegate.swift#L104). Let us know if you need anything else!

**Comment by zedwill** [comment]
Thanks @chauduyphanvu & @p158276
