### ISSUE TITLE
rewardedVideoAdDidDisappear erroneously called when clicking a MoPub ad

### ISSUE THREAD

**Issue by nrj** [mopub/mopub-ios-sdk#349]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.14.1

#### Device model and OS Version:
All, including simulator

#### Xcode Version:
Tested on 11 and 12

#### Ad Unit IDs used in reproducing the issue:
98c29e015e7346bd9c380b1467b33850
4f117153f5c24fa6a3a92b818a5eb630

#### Steps to reproduce the behavior:
1. Open a reward video or interstitial using the ad units above. 
2. Now interact with the ad by tapping until you are pushed to a website.
3. Notice that the `rewardedVideoAdDidDisappear` is called however the ad view controller is still visible.

#### Expected behavior:
`rewardedVideoAdDidDisappear` is only called when the ad is dismissed, as per the documentation.

#### Screen recording
[screen-recording.mov.zip](https://github.com/mopub/mopub-ios-sdk/files/5451895/screen-recording.mov.zip)

Edit:
Just confirmed the same problem exists with interstitials and the `interstitialDidDisappear` delegate method.

**Comment by nrj** [comment]
Just added a screen recording above.

**Comment by p158276** [comment]
Hi @nrj ,
Thanks for sharing the information. We are aware of this issue. We are currently checking internally. I will share the information here once we have any update.

Yoyo Lin
MoPub Team

**Comment by BorisMolch** [comment]
@p158276 do you have a timeline on this issue?

**Comment by p158276** [comment]
Hi @BorisMolch ,
We don't have a timeline on this at this moment. I will share the information here once we have any update.

**Comment by silviosav-SEGA-HARDlight** [comment]
Hi @p158276,

any news on this? This is breaking badly our logic and it doesn't look to be fixed in 5.15.0 either. Please provide any update because we're holding up our release due to this issue.

**Comment by p158276** [comment]
Hi @silviosav-SEGA-HARDlight ,
We'll address this problem in the coming SDK version. There's no timeline for now for the release. I'll comment here when we have any update.

**Comment by nindim** [comment]
Hi,

Is there any progress on this? This is a game-breaking bug for us and it's hampering our efforts to get ready for the looming ATT changes and release advanced bidding.

Thank you.

**Comment by p158276** [comment]
Hi @nindim ,
Thanks for reaching out. We don't have any timeline at this moment. I'll comment here when we have any update.
For the workaround here, you can try to check `rewardedVideoAdDidReceiveTapEventForAdUnitID` and see if the `rewardedVideoAdDidDisappear` is called due to the click. Please let me know if that works for you.

**Comment by p158276** [comment]
Fixed in v[5.16.0](https://github.com/mopub/mopub-ios-sdk/commit/d90f632b9a58a2ee8f533708883e77504c077d4f#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR8). Let us know if you continue seeing the issue!
