### ISSUE TITLE
Expose Consent Dialog ViewController

### ISSUE THREAD

**Issue by sgabello** [mopub/mopub-ios-sdk#352]
It would be great if you could make the Consent Dialog ViewController public so that we can customise the presentation (for example to look like a Modal Overlay) with a custom UIPresentationController.

**Comment by wacamoe** [comment]
Hello @sgabello,

The consent dialog is intentionally not customizable. More details about the consent mechanism can be found at https://developers.mopub.com/publishers/best-practices/gdpr-guide/
