### ISSUE TITLE
subscriberCellularProvider and currentRadioAccessTechnology are deprecated in iOS 12

### ISSUE THREAD

**Issue by saldous** [mopub/mopub-ios-sdk#355]
Just updating an old project and changed build target to iOS 12 and getting these warnings:

currentRadioAccessTechnology is deprecated in iOS 12.0
subscriberCellularProvider is deprecated in iOS 12.0

**Comment by p158276** [comment]
Hi @saldous ,
Thanks for the information. 
I'll circle back these back to the team for these depreciation.

Yoyo Lin
MoPub Team

**Comment by p158276** [comment]
Hi @saldous ,
The change will be realized in the following SDK release.

**Comment by p158276** [comment]
Hi @saldous 
This has been addressed in the [5.16.0](https://github.com/mopub/mopub-ios-sdk/releases/tag/5.16.0) release. Thank you again for reaching out.
