### ISSUE TITLE
Swift dependencies problems on 5.15.0

### ISSUE THREAD

**Issue by sgabello** [mopub/mopub-ios-sdk#361]
One line summary of the issue here

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.15.0
(Integrate the SDK Manually - MoPub Base SDK Excluding Native.zip)

#### Device model and OS Version:
iOS

#### Xcode Version:
12

#### Steps to reproduce the behavior:
After updating from 5.14.1 to 5.15.0 the project now introduce Swift dependencies not necessary before.
At building time, Xcode now require a Swift version to be set in the project settings.
After fixing that (set to v5), the compiler is now complaining as follow:
```/~project_folder/MoPubSDK/Internal/MRAID/MRController.m:13:13: 'MoPub-Swift.h' file not found```

**Comment by hmertkahraman** [comment]
Hi @sgabello ,

Thanks for reaching out. Is this the only error you're getting, do you have any additional errors or related warnings from XCode? Have you tried cleaning project and derived data, and rebuilding?

Moreover, do you happen to have a Objective C Bridging Header file?

Thanks,
Mert

**Comment by sgabello** [comment]
Hi Mert,

Sorry, I should have been more specific. The app is build in Objective-C and therefore no, I don't have an Objective-C Bridging Header File. Moreover I also shouldn't be asked to set a Swift version in the project settings.

There are no other related issues. I can confirm that I also rebuilt the app from scratch after cleaning the built project and deleted the Derived Data folder.

I'm attaching a screenshot for reference.

<img width="1440" alt="Screenshot 2020-12-28 at 10 33 07" src="https://user-images.githubusercontent.com/3297/103235532-0d802500-4908-11eb-939f-19d812d1ed50.png">

**Comment by IvanoBilenchi** [comment]
I'm having the same issue, also after upgrading from 5.14.1 to 5.15.0 (using manual integration, MoPub Base SDK Excluding Native.zip).

**Comment by hmertkahraman** [comment]
Hi @sgabello ,

Could you please try adding a Bridging Header? XCode should auto prompt to generate one if you attempt to add a Swift file (if that doesn't work please see [here](https://binbytes.com/blog/bridging-header-file-objective-c-in-swift) it should help).

If don't wish to set a Swift version in your project for a manual integration, please try using the distributed framework or Cocoapods with `use_frameworks!` entry.

Thanks,
Mert

**Comment by agrobost** [comment]
I'm having the same issue.

**Comment by sgabello** [comment]
Hi Mert,

Thanks for the feedback. Is "MoPub-Swift.h" supposed to be the bridging header? 

If so, it should be included in the zip file that you generate, as there are reference to it in your own code. Or at least you should update the SDK documentation to explain that from SDK v5.15.0 MoPub requires Swift also in Objective-C projects and a bridging header with a file name of "MoPub-Swift.h" should be included in the project.

If not... well... then that file (whatever it is...) is missing and it should be included in the distribution. ;)

**Comment by hmertkahraman** [comment]
Hi @sgabello ,

Objective C Bridging Header file is a standard protocol file defined by Apple for Swift <> Obj C compatibility. 

As it is a standard in iOS programming, we do not provide a best practice around it, nor ship it with our distributed package as each iOS project accepts one and SDKs would not own that responsibility.

Here is the official documentation for it:
https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift

Hope this answers your question!

Mert

**Comment by sgabello** [comment]
Thanks @hmertkahraman.

Partially...
I still don't understand what is the "MoPub-Swift.h" file referenced in your code and missing in the SDK.

Thanks,
Andrea

**Comment by hmertkahraman** [comment]
Hi @sgabello ,

Sure! So, MoPub-Swift.h file is actually present in the SDK, and we do ship it. But it appears that in your project, there's no file to expose it to the Swift <> Obj-C compatibility level. Therefore it appears like it's missing, but it's actually there. Would you also please check the comment described [here](https://github.com/mopub/mopub-unity-sdk/issues/161#issuecomment-754582212)?

Thanks,
Mert

**Comment by sgabello** [comment]
Hi @hmertkahraman 

Can you please check [this:](https://github.com/mopub/mopub-ios-sdk/releases/download/5.15.0/mopub-nonnative-5.15.0.zip)

The file is not included in the zip file.

<img width="729" alt="Screenshot 2021-01-05 at 07 56 03" src="https://user-images.githubusercontent.com/3297/103654595-b55ea980-4f2b-11eb-90f6-016a9032bb50.png">

**Comment by hmertkahraman** [comment]
Hi @sgabello ,

A correction about the availability of this file:
MoPub-Swift.h is a file automatically generated by Xcode to allow the Objective-C parts of our code to see the Swift parts.

Can we check in if our [initial recommendation](https://github.com/mopub/mopub-ios-sdk/issues/361#issuecomment-754123133) worked for you?

Thanks!
Mert

**Comment by sgabello** [comment]
Hi @hmertkahraman,

Thanks for the clarification!

I'm now trying to switch to the distributed framework as suggested, but I'm now getting errors with the import of `MPAdView.h`.

Does the use of the framework change the way that the code has to be implemented in the app ViewController compared to the base manual integration? Does `#import "MPAdView.h"` need to change?

Thanks,
Andrea

**Comment by sgabello** [comment]
Ok, I think I resolved the issue by replacing `#import "MoPub.h"` with `#import <MoPub/MoPub.h>` and `#import "MPAdView.h"` with `#import <MoPub/MPAdView.h>`.

It would be nice if the documentation explained the use of the different `#import` statements between the implementation of the raw code based SDK and the framework version.

Thanks for the help.

**Comment by hmertkahraman** [comment]
Hi @sgabello ,

Thanks for mentioning the solution [here](https://github.com/mopub/mopub-ios-sdk/issues/361#issuecomment-756553442), and we appreciate your feedback.

Mert

**Comment by Oklahomawhore** [comment]
you have to change all imports of `#import MoPubSDK-Swift.h` to `#import {Your_Target_Name}-Swift.h` because the name is different for each project when generating the swift header for objective-c

> Hi @hmertkahraman,
> 
> Thanks for the feedback. Is "MoPub-Swift.h" supposed to be the bridging header?
> 
> If so, it should be included in the zip file that you generate, as there are reference to it in your own code. Or at least you should update the SDK documentation to explain that from SDK v5.15.0 MoPub requires Swift also in Objective-C projects and a bridging header with a file name of "MoPub-Swift.h" should be included in the project.
> 
> If not... well... then that file (whatever it is...) is missing and it should be included in the distribution. ;)
