### ISSUE TITLE
Support for SKAdNetwork 2.2 post view attribution

### ISSUE THREAD

**Issue by zedwill** [mopub/mopub-ios-sdk#364]
iOS 14.5 brings the new SKAdNetwork version 2.2.
SKAdNetwork 2.2 adds support for post view attribution and it is incompatible with the current mopub SDK.
It would be nice for the advertisers to have support for SKADNetwork 2.2 to enable post view attribution of their installs.

- [ X] I am submitting a bug report for existing functionality
- [ X] I visited https://developers.mopub.com/ and found no answer
- [ X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.15.0
#### Device model and OS Version:
iOS 14.5
#### Xcode Version:
Xcode 12
#### Steps to reproduce the behavior:
Apple has recently updated this documentation: https://developer.apple.com/documentation/storekit/skadnetwork/generating_the_signature_to_validate_view-through_ads

Describing how to enable post view attribution on the new 2.2

#### Expected behavior:
The SDK would need to be updated, at least according to this instructions from the previous page

```
To provide a view-through ad and initiate a validation, the app calls startImpression(_:completionHandler:), presents the ad, and then calls endImpression(_:completionHandler:). The two methods use the same instance of SKAdImpression, which contains signature, which is the signature the ad network generates.
```

Also, mopub implementation for skadnetwork, described in https://developers.mopub.com/dsps/best-practices/skadnetwork/
would need to be updated to include in seatbid.bid.ext.skadn the new 2.2 parameter called fidelity type fidelity-type

The change would be ideally coordinated with the other extension sponsors listed here:
https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/extensions/community_extensions/skadnetwork.md

#### Observed behavior:
No support for 2.2 impression signing

#### Evidence:
Lack of fidelity-type in the signing signature

**Comment by p158276** [comment]
Hi @zedwill ,
Thanks for reaching out. We are aware of the change. We will provide more updates on our support and timing shortly.

Yoyo Lin
MoPub team
