### ISSUE TITLE
Apple rejects GDPR at Personalise your experience Dialog

### ISSUE THREAD

**Issue by ndhieuvn212** [mopub/mopub-ios-sdk#365]
when Mobpub show consent GDPR dialog it invokes Android information "... On android devices, enable Opt Out of Ads Personalization setting..." See the enclose image for detail the content dialog. Apple rejects it. Here is the full message from Apple:

From Apple

    2. 3 Performance: Accurate Metadata

Guideline 2.3.10 - Performance - Accurate Metadata. We noticed that your app or its metadata includes irrelevant third-party platform information.
**Specifically, your app includes Android references in the Personalise your experience banner**. Referencing third-party platforms in your app or its metadata is not permitted on the App Store unless there is specific interactive functionality.

Next Steps 

To resolve this issue, please remove all instances of this information from your app and its metadata, including the app description, promotional text, What's New info, previews, and screenshots.

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.15

#### Device model and OS Version:
14.2
#### Xcode Version:
12.2
#### Ad Unit IDs used in reproducing the issue:
can use any Unit ID
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
Make new install then launch the app then we see the dialog.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

The message does not  include text which related Android.

#### Observed behavior:
As concisely as possible, describe the observed behavior.
See the dialog, it has Android in the text then apple rejects by his rule.

#### Evidence:
Device log files, Network log file, etc.
![Image from iOS](https://user-images.githubusercontent.com/2195276/106716653-4743fa00-6631-11eb-8f38-cd9cc673d011.png)

**Comment by Neptuns** [comment]
The same problem on Android. I don't want to show users irrelevant iOS information.

**Comment by chauduyphanvu** [comment]
Thanks for letting us know! I've relayed the report to the rest of the team and we'll share an update soon. Stay tuned!

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
Hi all, this issue has been fixed. iOS devices should now receive iOS-specific GDPR metadata/messages. Thanks for your patience!
