### ISSUE TITLE
Unable to build for simulator on Apple Silicon

### ISSUE THREAD

**Issue by tahirmt** [mopub/mopub-ios-sdk#367]
Unable to build for simulator on Apple Silicon. Received error `Could not find module 'MoPub' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64`

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
App builds for simulator

#### Observed behavior:
Received error `Could not find module 'MoPub' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64`

**Comment by p158276** [comment]
Hi @tahirmt ,
Thanks for bringing that to our attention. Currently, we don't support arm64 iOS Simulators on Apple Silicon Macs because the late OM SDK library does not support arm64 simulator architectures. I'll circle back when there is any update.

Yoyo Lin
MoPub Team

**Comment by vrtcalsdkdev** [comment]
@p158276 If I understand correctly, IAB now supports arm64 in the v1.3.15 release of the OM SDK which was released about a month and a half ago on 2020-12-18:

![image](https://user-images.githubusercontent.com/62034899/107296501-5efef200-6a26-11eb-838b-5dd4126d0a49.png)

**Comment by p158276** [comment]
Hi @vrtcalsdkdev ,
Thanks for the useful information here! MoPub currently is using OM static library which doesn't contain arm64 architecture for simulators. The screenshot you provided is the OM xcframework library. We'll circle back to our engineering team and provide the update when support.

Yoyo Lin
MoPub Team

**Comment by wacamoe** [comment]
Hi @vrtcalsdkdev - Thank you again for the support. We are evaluating how to address running in a Apple Silicon based simulator for both internal and external use cases. Any updates here will be included in subsequent SDK update. Unfortunately the only workaround here is to use the simulator on a non-Apple Silicon Mac, or use an actual device for now.

Stay tuned....

**Comment by Codewaves** [comment]
Hi,
Any news on this issue?

**Comment by p158276** [comment]
Hi @Codewaves , 
Thanks for the follow-up.  This issue has been fixed internally and will be released in the following SDK release. We will provide more information when there's any update.

**Comment by chauduyphanvu** [comment]
This is now supported in [v5.17.0](https://github.com/mopub/mopub-ios-sdk/blob/master/CHANGELOG.md#version-5170-may-11-2021) of the MoPub iOS SDK. Check it out and let us know if you have any questions!
