### ISSUE TITLE
The ad closes and loads the next ad, but ad didn’t actually load

### ISSUE THREAD

**Issue by guojunliu** [mopub/mopub-ios-sdk#368]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.15.0

#### Device model and OS Version:
iPhone11 & iOS14

#### Xcode Version:
Xcode 12.0

#### Ad Unit IDs used in reproducing the issue:
b79ee2d1003e41639220efda16ec137e

#### Steps to reproduce the behavior:
Load a new ad immediately after the ad is closed

/**
 * This method is called when a rewarded video ad has been dismissed.
 */
- (void)rewardedVideoAdDidDisappearForAdUnitID:(NSString *)adUnitID {
    BOOL b = [MPRewardedVideo hasAdAvailableForAdUnitID:kMopubAdUnitId];
    NSLog(@"[LOG] call %@ and hasAdAvailableForAdUnitID is %@",NSStringFromSelector(_cmd),b?@"YES":@"NO");
    
    
    NSLog(@"[LOG] ----------------------");
    NSLog(@"[LOG] will load next rewardAd");
    [MPRewardedVideo setDelegate:self forAdUnitId:kMopubAdUnitId];
    [MPRewardedVideo loadRewardedVideoAdWithAdUnitID:kMopubAdUnitId withMediationSettings:nil];
}

#### Expected behavior:
Load new ad

#### Observed behavior:
Ads didn’t actually load

#### Evidence:
![code2](https://user-images.githubusercontent.com/6713422/107139730-5cce6200-6958-11eb-9e96-215238e39e1e.png)
![code1](https://user-images.githubusercontent.com/6713422/107139733-60fa7f80-6958-11eb-862b-53d0996c3bc9.png)
<img width="1400" alt="code" src="https://user-images.githubusercontent.com/6713422/107139736-635cd980-6958-11eb-8af6-776c2d9fe164.png">

Detailed description ：https://guojunliu.github.io/MopubUpdateIssues/
Reproduce Demo: https://github.com/guojunliu/MopubIssuesDemo

**Comment by guojunliu** [comment]
ready and playedAd are not reset before  call rewardedVideoAdDidDisappearForAdUnitID

**Comment by guojunliu** [comment]
![E2EFC432-90C7-41A7-9A21-EFE3C5BA4613](https://user-images.githubusercontent.com/6713422/107140432-cb152380-695c-11eb-9e97-fb406f2c1d77.png)

As a result, the next time the ad is loaded, the judgment is wrong, and the new ad cannot be loaded.

**Comment by p158276** [comment]
Hi @guojunliu ,
Thank you for putting together the bug report. This issue happens because of OM, the MoPub SDK will take a certain amount of time (in milliseconds) to deallocate each ad when it’s closed. A workaround to mitigate it is to delay the next ad request by 1000ms (1s) after closing the ad. Doing so will allow the MoPub SDK time to reset, and you can make another ad request afterwards.
Note that the recommendation of 1000ms is not definitive. It is encouraged to test with an amount that works for you. 
We'll fix it in the following SDK release. Let us know if you have any other concerns or questions.

Yoyo Lin
MoPub Team

**Comment by p158276** [comment]
Fixed in v[5.16.0](https://github.com/mopub/mopub-ios-sdk/commit/d90f632b9a58a2ee8f533708883e77504c077d4f#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR8). Let us know if you continue seeing the issue!
