### ISSUE TITLE
Privacy icon image appears on top of the text in native ads using AdMob

### ISSUE THREAD

**Issue by amsdamsgram** [mopub/mopub-ios-sdk#369]
- [ ] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.15.0

#### Device model and OS Version:
iPhone X 14.2

#### Xcode Version:
12.2

#### Ad Unit IDs used in reproducing the issue:
5e8e7e3240c24fd18d9eb66b7ef0a37d

#### Steps to reproduce the behavior:
When displaying a native ad using MoPub-AdMob-Adapters v7.68.0.2, the privacy icon image appears on the text of the ad. 
Here is the code we use to request the ad:
```
// RNNativeAdView.m

MPStaticNativeAdRendererSettings *settings = [[MPStaticNativeAdRendererSettings alloc] init];
    settings.renderingViewClass = [RNNativeAdView class];
    // Mopub rendered
    MPNativeAdRendererConfiguration *mopubConfiguration = [MPStaticNativeAdRenderer rendererConfigurationWithRendererSettings:settings];
    // Google rendered
    MPNativeAdRendererConfiguration *googleConfiguration = [MPGoogleAdMobNativeRenderer rendererConfigurationWithRendererSettings:settings];

    MPNativeAdRequest *adRequest = [MPNativeAdRequest requestWithAdUnitIdentifier:adUnitId rendererConfigurations:@[mopubConfiguration, googleConfiguration]];
    
    MPNativeAdRequestTargeting *targeting = [MPNativeAdRequestTargeting targeting];
    targeting.desiredAssets = [NSSet setWithObjects:kAdTitleKey, kAdTextKey, kAdCTATextKey, kAdIconImageKey, kAdMainImageKey, kAdStarRatingKey, nil]; //The constants correspond to the 6 elements of MoPub native ads
    adRequest.targeting = targeting;
```

It seems like it is displayed automatically as in the code, we don't display it.
How can we make it appear so that it is not on top of the text of the ad?

#### Expected behavior:
Privacy icon image should not appear on top of the text of the ad.

#### Evidence:
<img width="356" alt="Screen Shot 2021-02-10 at 12 29 47 PM" src="https://user-images.githubusercontent.com/1591702/107530703-6ce67b80-6bbc-11eb-8ee7-e0ae0d75443f.png">

**Comment by chauduyphanvu** [comment]
@amsdamsgram, your ad unit ID is currently serving Marketplace native ads so I couldn't reproduce this issue via that ID. However, have you tried [this option](https://developers.mopub.com/publishers/mediation/networks/google/#adchoices-options) to set the placement of the AdChoices icon?

Vu Chau
MoPub Team

**Comment by amsdamsgram** [comment]
Hi Vu,

Thank you for your answer. I was not aware of this option.
Although shouldn't it respect the UI I made in the xib file that is linked to my `RNNativeAdView`?
I have a privacyInformationIconImageView property.

**Comment by chauduyphanvu** [comment]
@amsdamsgram, it should. I have the `privacyInformationIconImageView` too but my ads aren't displaying the Ad Choices icon so I couldn't verify the issue here.

Do you have another ad unit ID reliably targeting the same AdMob line item that we could test?

**Comment by amsdamsgram** [comment]
Not really.
But it's okay, it is displayed correctly now even though it doesn't respect the xib.

Thanks for your help!
