### ISSUE TITLE
`Type 'MPInterstitialAdController' has no member 'forAdUnitId'` in swift project

### ISSUE THREAD

**Issue by Handsome2734** [mopub/mopub-ios-sdk#370]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
I have a project in Swift 5. When calling `MPInterstitialAdController.forAdUnitId` XCode fires an error.
![image](https://user-images.githubusercontent.com/5567825/108463579-99d01800-72b9-11eb-8b7a-137321fde028.png)

This is my Podfile, hope it helps.
![image](https://user-images.githubusercontent.com/5567825/108463737-db60c300-72b9-11eb-8901-cf8c14316999.png)

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by Handsome2734** [comment]
`MPNativeAdRequest` has a similar issue.

![image](https://user-images.githubusercontent.com/5567825/108471530-7e1f3e80-72c6-11eb-8c08-0f80adc69dd7.png)

**Comment by chauduyphanvu** [comment]
@Handsome2734, can you try calling it like `interstitialAd = MPInterstitialAdController(forAdUnitId: adUnit.id)` and `MPNativeAdRequest(adUnitIdentifier: adUnit.id, rendererConfigurations: rendererConfigurations)`?

Vu Chau
MoPub Team

**Comment by Handsome2734** [comment]
> @Handsome2734, can you try calling it like `interstitialAd = MPInterstitialAdController(forAdUnitId: adUnit.id)` and `MPNativeAdRequest(adUnitIdentifier: adUnit.id, rendererConfigurations: rendererConfigurations)`?
> 
> Vu Chau
> MoPub Team

It seems not working either.
![image](https://user-images.githubusercontent.com/5567825/108582377-d65d4b80-736d-11eb-8564-1553c50e9806.png)

For MPNativeAdRequest, xcode can autocomplete with the initialization method.
![image](https://user-images.githubusercontent.com/5567825/108582451-6b604480-736e-11eb-9f43-bef700f81cd5.png)
But I can not call it like this...
![image](https://user-images.githubusercontent.com/5567825/108582454-71562580-736e-11eb-9350-93b96b9f9f61.png)

**Comment by victorcampeanu** [comment]
same issue

**Comment by chauduyphanvu** [comment]
Hi all, are you able to build our iOS sample app on this repository? It also uses Swift 5 and we can build it without any issues.

If it works for you, feel free to share your app project and we can give it a try on our end. If it doesn't work for you, let us know other setup/tool details you might have so we can compare with ours.

**Comment by Handsome2734** [comment]
After upgrade to 5.16.0, add `import MoPubSDK` at file begining solves my issue.

**Comment by chauduyphanvu** [comment]
@Handsome2734 - good to hear! Doing that is in line with what we do here in our sample app: https://github.com/mopub/mopub-ios-sdk/blob/484b1fff1a136023e1658ee9b5a64b89a504cd7b/Canary/Canary/Formats/InterstitialAdDataSource.swift#L9

Let us know if you continue seeing the issue.

**Comment by jamesmorrisapps** [comment]
@chauduyphanvu our engineers also just tried that, but we are still seeing an error

**Comment by chauduyphanvu** [comment]
@jamesmorrisapps, which Xcode and Swift versions are you using? My suggestion is to try to compile our sample app on this repository. It should work. Then we can work on narrowing down the version differences between your team and our team.

**Comment by jamesmorrisapps** [comment]
@chauduyphanvu Xcode 12.4, Swift 5

**Comment by chauduyphanvu** [comment]
@jamesmorrisapps, thanks for confirming the versions. They're the same as what we use. At this point, it might be an external dependency/factor that's blocking your build. 

You can check out our sample app on this repository and let us know if it builds for you.

**Comment by jamesmorrisapps** [comment]
@chauduyphanvu sure thing. Gotcha. We'll take a look and let you know if we are still running into the same issue. Thanks!

**Comment by Handsome2734** [comment]
Hi guys, I found out that use binary version work like a charm.

**Comment by meyer-solutions** [comment]
I'm using the Cocoapod method to integrate the library and after adding NS_SWIFT_NAME to the method declaration (after unlocking the file in Xcode) the project compiles again. Very strange...

**Comment by chauduyphanvu** [comment]
> Hi guys, I found out that use binary version work like a charm.

@Handsome2734, thanks for the confirmation. How were you integrating MoPub before?

**Comment by Handsome2734** [comment]
> > Hi guys, I found out that use binary version work like a charm.
> 
> @Handsome2734, thanks for the confirmation. How were you integrating MoPub before?

Just `pod mopub-ios-sdk`. Now I build it into binary and link to my project manually.

**Comment by chauduyphanvu** [comment]
Closing this issue as the OP has found the resolution.
