### ISSUE TITLE
Cocoapods still downloads old version (5.15.0)

### ISSUE THREAD

**Issue by saldous** [mopub/mopub-ios-sdk#371]
I have this in my podfile:

`pod 'mopub-ios-sdk', '~> 5.13'`

but it still downloads 5.15.0 and not 5.16.0. Any ideas?

**Comment by p158276** [comment]
Hi @saldous ,
Thanks for reaching out. The pod 'mopub-ios-sdk', '~> 5.13' seems to fetch 5.16.1 on my end. Can you try the following command to clean the cache and update the repo again?

```
pod cache clean --all
pod repo update
```

Yoyo Lin
MoPub Team

**Comment by saldous** [comment]
I think it is because I'm also using GoogleMobileAdsMediationMoPub. I think they need to update.

**Comment by p158276** [comment]
Hi @saldous ,
Thanks for following up. When it goes to Admob mediate MoPub, Admob is the one maintaining the adapters. You can reach out to Admob team and check for the update.

Closing the issue here.
