### ISSUE TITLE
Second time loaded Interstitial Ads are not showing.

### ISSUE THREAD

**Issue by can-soykarafakili** [mopub/mopub-ios-sdk#374]
The closed issues #356 and #368 are still happening with the same steps in `v: 5.16.1` for Interstitial Ads. Especially this specific [comment](https://github.com/mopub/mopub-ios-sdk/issues/356#issuecomment-744572584).

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version: 
5.16.1

#### Device model and OS Version: 
MacBook Pro (13-inch, 2016), Simulator (iPhone 8 & iOS 14.3)

#### Xcode Version: 
12.3 (12C33)

#### Ad Unit IDs used in reproducing the issue:
Interstitial: `a50d6ad8b2b84ea0af8049b8dfd32126`

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

- Follow the documentation step by step and integrate interstitial ad
- Load an ad for the first time.
- First ad displays without any problem.
- Load a new ad after the first one is closed.
- The second ad (and the ones come after that) is not showing on the screen.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

The second ad should be displaying properly. Like it did perfectly until `MoPub v: 5.14.1.`

#### Observed behavior:
As concisely as possible, describe the observed behavior.

The related `didLoad` methods fire immediately after the request but it does not show/display any ads.

#### Evidence:
Device log files, Network log file, etc.

Logs for the first Interstitial Ad (Shows without any issues)

```
[MoPub][MPInterstitialAdManager][a50d6ad8b2b84ea0af8049b8dfd32126] Attempting to load ad
[MoPub][MPInterstitialAdManager] Interstitial ad view is fetching ad type: custom
[MoPub][HyBidMoPubMediationInterstitialCustomEvent] Looking for adapter class named HyBidMoPubMediationInterstitialCustomEvent.
[MoPub][MPInterstitialAdManager][a50d6ad8b2b84ea0af8049b8dfd32126] Ad loaded
[MoPub][MPInterstitialAdManager][a50d6ad8b2b84ea0af8049b8dfd32126] Attempting to show ad
```
Logs for the second Interstitial Ad (Ad is not visible in the screen)

```
[MoPub][MPInterstitialAdManager][a50d6ad8b2b84ea0af8049b8dfd32126] Attempting to load ad
[MoPub][MPInterstitialAdManager][a50d6ad8b2b84ea0af8049b8dfd32126] Attempting to show ad
```

**Comment by dravyan** [comment]
Hi @can-soykarafakili , thank you for the report. We will take a look and get back to you.

Thanks,
MoPub Team

**Comment by dravyan** [comment]
@can-soykarafakili, What callback have you subscribed to to receive ad closure notification?. Please make sure to use [didDismiss](https://github.com/mopub/mopub-ios-sdk/blob/38ee86fa959fe62288597d7d7c15adf2c6e7ddce/Canary/Canary/Formats/InterstitialAdDataSource.swift#L192) callback introduced in 5.16.x SDK. This should resolve the issue.

**Comment by can-soykarafakili** [comment]
Hi @dravyan,

Thank you for your reply. Replacing `willDisappear:` and `didDisappear: ` to `willDismiss:` and `didDismiss:` in `MPInterstitialAdControllerDelegate` helped the issue. 👍 

But for my application changing this was the part of the solution. Since I am using a Custom Event Class, I had to change the `fullscreenAdAdapterAdWillDisappear: `and `fullscreenAdAdapterAdDidDisappear:` to `fullscreenAdAdapterAdWillDismiss:` and `fullscreenAdAdapterAdDidDismiss:` in `MPFullscreenAdAdapterDelegate` as well. 

I believe those methods in `MPFullscreenAdAdapterDelegate` are also deprecated however, they are not marked like that in the SDK. 🤔 They should also be marked as `Deprecated` like in `MPInterstitialAdControllerDelegate`. So that it can avoid future confusions. 👍 

Thanks again and stay healthy!! 😄

**Comment by dravyan** [comment]
@can-soykarafakili , thanks for the update. `fullscreenAdAdapterAdWillDisappear` and `fullscreenAdAdapterAdDidDisappear` are not deprecated in the current release. In order to receive ad dismissal notification, it is required to subscribe to `fullscreenAdAdapterAdDidDismiss`. Reference to the [Fullscreen callbacks](https://developers.mopub.com/networks/integrate/build-adapters-ios/#quick-start-for-fullscreen-ads) if you are using custom event class.
