### ISSUE TITLE
Support for SwiftUI (example code?)

### ISSUE THREAD

**Issue by darecki** [mopub/mopub-ios-sdk#375]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.16.1
#### Xcode Version:
12.4

Hi. Are you planning to support SwiftUI apps? Some example code on how to integrate the framework in SwiftUI Views would be very appreciated. Thanks.

**Comment by chauduyphanvu** [comment]
@darecki, thanks for the inquiry. We currently do not have plans to support SwiftUI. I'll update this thread when the plan changes.

Vu Chau
MoPub Team

**Comment by adampax** [comment]
@darecki Here is an example app I put together showing how to use Banner and Interstitial ads in SwiftUI: https://github.com/adampax/MoPubSwiftUIDemo
