### ISSUE TITLE
No ads found for ad unit - Facebook and Unity networks

### ISSUE THREAD

**Issue by swipip** [mopub/mopub-ios-sdk#376]
One line summary of the issue here

Ads fail to load using Facebook and UnityAds networks, logging "[MoPub][MPInterstitialAdManager] No ads found for ad unit: 399dfede4010410f8a8f8b3c0318195b".

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:

- 5.16.1

#### Device model and OS Version:

- iPhone XS running iOS 14.2

#### Xcode Version:

- Xcode 12.4

#### Ad Unit IDs used in reproducing the issue:

- 399dfede4010410f8a8f8b3c0318195b

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

- Implement the MoPub SDK
- Initialize following the documentation
- Wait for initialization callback
- Load an intersticial ad using Facebook or UnityAd networks

#### Expected behavior:

An ad should load 

#### Observed behavior:

No ad loads 

#### Evidence:
Device log files, Network log file, etc.

Logs using Facebook: 

	[MoPub][MoPub] SDK initialized and ready to display ads.
	[MoPub][GoogleAdMobAdapterConfiguration] Google Mobile Ads SDK initialized succesfully.
	[MoPub][MPInterstitialAdManager][399dfede4010410f8a8f8b3c0318195b] Attempting to load ad
	[MoPub][MPInterstitialAdManager] Interstitial ad view is fetching ad type: custom
	[MoPub][FacebookInterstitialCustomEvent] Looking for adapter class named FacebookInterstitialCustomEvent.
	[MoPub][FacebookInterstitialCustomEvent] Loading Facebook interstitial
	[MoPub][MPInterstitialAdManager] Interstitial ad view is fetching ad type: clear
	[MoPub][MPInterstitialAdManager] No ads found for ad unit: 399dfede4010410f8a8f8b3c0318195b
        [MoPub] Add error. The operation couldn’t be completed. (com.mopub.iossdk error 0.)

Logs using MoPub:

	[MoPub][MPViewabilityManager] Initialized OM SDK version: 1.3.4-Mopub
	[MoPub][MoPub] SDK initialized and ready to display ads.
	[MoPub][GoogleAdMobAdapterConfiguration] Google Mobile Ads SDK initialized succesfully.
	[MoPub][MPInterstitialAdManager][399dfede4010410f8a8f8b3c0318195b] Attempting to load ad
	[MoPub][MPInterstitialAdManager] Interstitial ad view is fetching ad type: custom
	[MoPub][UnityAdsInterstitialCustomEvent] Looking for adapter class named UnityAdsInterstitialCustomEvent.
	[MoPub][MPMediationManager] Cached SDK initialization parameters for UnityAdsAdapterConfiguration:
	[MoPub][MPInterstitialAdManager] Interstitial ad view is fetching ad type: clear
	[MoPub][MPInterstitialAdManager] No ads found for ad unit: 399dfede4010410f8a8f8b3c0318195b
        [MoPub] Add error. The operation couldn’t be completed. (com.mopub.iossdk error 0.)

**Comment by chauduyphanvu** [comment]
@swipip, did you set up demand for Facebook Audience Network and Unity Ads for the ad unit ID `399dfede4010410f8a8f8b3c0318195b`? It appears there might only be MoPub Marketplace demand and that'd be one of the reasons why it's not serving mediated ads.

If you have questions about setting up your waterfall, get in touch with the team at support@mopub.com. Let us know if you have any questions!

Vu Chau
MoPub Team

**Comment by swipip** [comment]
@chauduyphanvu thanks for your reply. We did set up the networks, but since our app is in production we defaulted the settings to the Marketplace. 
Yet when we activate Facebook and/or unity, the logs (mentioned in the original message) tell me that no ad gets found for the ad unit.

**Comment by chauduyphanvu** [comment]
We aren't able to help troubleshoot that without knowing your actual placement IDs from Facebook and Unity. My recommendation for this would be to enable test mode from [Facebook](https://developers.facebook.com/docs/audience-network/guides/test/) and [Unity Ads](https://support.unity.com/hc/en-us/articles/218324523-How-do-I-enable-a-device-for-testing-) to test your implementation. 

If you get back an ad, then that means your integration is OK and that your mediation placements might need to be revalidated. If that is the case, I'd recommend speaking with the ad networks in question for additional assistance.

Let us know if you need anything else!
