### ISSUE TITLE
Mopub ads not loading on 5.16.1?

### ISSUE THREAD

**Issue by ebarellar** [mopub/mopub-ios-sdk#378]
#### MoPub SDK Version:
5.16.1

#### Device model and OS Version:
iPhone 6s and simulator

#### Xcode Version:
12.4

#### Ad Unit IDs used in reproducing the issue:
Both mine and test ad unit "b195f8dd8ded45fe847ad89ed1d016da"

#### Steps to reproduce the behavior:
Load a banner ad

#### Expected behavior:
Ads from Mopub guaranteed creatives or test ad unit should be presented

#### Observed behavior:
Ads appear to load but nothing is being presented on screen, work fine on 5.15.0. Tests with Admob test ads work fine, seems to only be affecting mopub

#### Evidence:
Attach success and error cases. In the error case the routine to open the lower bar after the ad is loaded is called, but nothing seems to be presented when it comes from mopub.
![error](https://user-images.githubusercontent.com/34749672/111088836-bb09da00-84ee-11eb-8747-b62c07a2fe98.png)
![errorscreen](https://user-images.githubusercontent.com/34749672/111088837-bc3b0700-84ee-11eb-9f76-4568b5557446.jpg)
![success](https://user-images.githubusercontent.com/34749672/111088838-bd6c3400-84ee-11eb-81db-c5bd86a55f30.jpg)
![successful](https://user-images.githubusercontent.com/34749672/111088839-bd6c3400-84ee-11eb-99db-226c971f167d.png)

**Comment by ebarellar** [comment]
OK, seems I found the issue

I got a bunch of constraint problems in the console
```
2021-03-14 18:21:19.756643-0600 Tracin Buddy[20952:268884] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fab020cb760 h=--& v=--& com.mopub.adcontainer.height == 50   (active, names: com.mopub.adcontainer:0x7fab06c2c930 )>",
    "<NSLayoutConstraint:0x7fab09ecaa60 UILayoutGuide:0x7fab09ec15c0'UIViewSafeAreaLayoutGuide'.top == UILayoutGuide:0x7fab020d3d70'UIViewSafeAreaLayoutGuide'.top   (active)>",
    "<NSLayoutConstraint:0x7fab09e8e500 UILayoutGuide:0x7fab09ec15c0'UIViewSafeAreaLayoutGuide'.bottom == UILayoutGuide:0x7fab020d3d70'UIViewSafeAreaLayoutGuide'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fab09e9f920 'UIViewSafeAreaLayoutGuide-bottom' V:[UILayoutGuide:0x7fab09ec15c0'UIViewSafeAreaLayoutGuide']-(0)-|   (active, names: '|':MPAdViewOverlay:0x7fab09ec3c10 )>",
    "<NSLayoutConstraint:0x7fab09ec5870 'UIViewSafeAreaLayoutGuide-bottom' V:[UILayoutGuide:0x7fab020d3d70'UIViewSafeAreaLayoutGuide']-(52)-|   (active, names: com.mopub.adcontainer:0x7fab06c2c930, '|':com.mopub.adcontainer:0x7fab06c2c930 )>",
    "<NSLayoutConstraint:0x7fab09e589a0 'UIViewSafeAreaLayoutGuide-top' V:|-(0)-[UILayoutGuide:0x7fab09ec15c0'UIViewSafeAreaLayoutGuide']   (active, names: '|':MPAdViewOverlay:0x7fab09ec3c10 )>",
    "<NSLayoutConstraint:0x7fab06c6b550 'UIViewSafeAreaLayoutGuide-top' V:|-(0)-[UILayoutGuide:0x7fab020d3d70'UIViewSafeAreaLayoutGuide']   (active, names: com.mopub.adcontainer:0x7fab06c2c930, '|':com.mopub.adcontainer:0x7fab06c2c930 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fab09e9f920 'UIViewSafeAreaLayoutGuide-bottom' V:[UILayoutGuide:0x7fab09ec15c0'UIViewSafeAreaLayoutGuide']-(0)-|   (active, names: '|':MPAdViewOverlay:0x7fab09ec3c10 )>
```

After the ad is loaded I increase the size of the safe area based on the ad size, then place the ad inside this extra safe area. If I remove this line the ad shows as expected
`self.additionalSafeAreaInsets = UIEdgeInsets(top: 0, left: 0,
                                                     bottom: adSize.height + 2.0,
                                                     right: 0)`

Seemed to work fine in older release. I will work in a fix on my part. Just want to be sure if my old routine is wrong and I should't place the add inside the safe area

**Comment by p158276** [comment]
Hi @ebarellar ,
Thanks for reaching out. You're right. The safe area shouldn't be changed between request and ad shows. Besides, the ad should be placed within the safe area. Otherwise, it might be cropped in some specific devices. Feel free to let us know if you have any other questions.

Yoyo Lin
MoPub Team
