### ISSUE TITLE
No bitcode support in 5.16.1

### ISSUE THREAD

**Issue by 2energycell** [mopub/mopub-ios-sdk#379]
One line summary of the issue here

- [X] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Evidence:

Showing All Messages
Bitcode bundle could not be generated because '.../Build/Products/Release-iphoneos/mopub-ios-sdk/libmopub-ios-sdk.a(CellularService.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/nikita/Library/Developer/Xcode/DerivedData/IASDK-aijlnmhzmizdthawfqatsdlchrfe/Build/Products/Release-iphoneos/mopub-ios-sdk/libmopub-ios-sdk.a' for architecture armv7

**Comment by hmertkahraman** [comment]
Hi @2energycell ,

Thanks for reaching out. Can we ask for some additional details, what version of iOS device are you running this on? And did you try cleaning Derived Data and retrying? Also, would you please be able to retry with 5.16.2 hotfix that was released recently?

Thanks,
MoPub Team

**Comment by 2energycell** [comment]
any version, when compiling an app with mopub inside, it will not compile until bitcode is disabled; this is a regression, it wasn't so before the 5.16

**Comment by hmertkahraman** [comment]
Are you building your project from Unity to iOS? If so can you please retry reinstalling MoPub Unity Plugini, and upgrading your Unity IDE's EDM to 1.2.164+ or latest version available and have it run again?
