### ISSUE TITLE
"Can't merge user_target_xcconfig for pod targets" when installing MoPub FAN adapter

### ISSUE THREAD

**Issue by dfabulich** [mopub/mopub-ios-sdk#381]
When you attempt to `pod install` the pods `mopub-ios-sdk/Core` and `MoPub-FacebookAudienceNetwork-Adapters`, an error results.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

(A similar PR has been filed https://github.com/mopub/mopub-ios-sdk/pull/345 to address this issue, but the PR doesn't make it clear that this issue reproduces easily just installing the current latest MoPub with MoPub's own FAN adapters.)

#### MoPub SDK Version:

mopub-ios-sdk/Core (5.16.2)
MoPub-FacebookAudienceNetwork-Adapters/Network (6.3.1.0)

#### Device model and OS Version:

Any

#### Xcode Version:

12.4

CocoaPods version 1.10.1

#### Ad Unit IDs used in reproducing the issue:

Any

#### Steps to reproduce the behavior:
To reproduce the behavior, create a new iOS App Xcode Project, run `pod init` to create a new `Podfile`, and use this as the `Podfile` content:

```ruby
platform :ios, '14.0'

target 'MopubFacebookPodsConflict' do
  use_frameworks!

  pod 'mopub-ios-sdk/Core'
  pod 'MoPub-FacebookAudienceNetwork-Adapters'
end
```

Then run `pod install`.

Alternately, for your convenience, I've provided a sample git repository. https://github.com/dfabulich/MopubFacebookPodsConflict In the first commit, we create an Xcode project, then, in the second commit, we `pod init`, and then, in the third commit, we create a `Podfile` and `Podfile.lock`. You can reproduce the problem by running `pod install` in that repository.

#### Expected behavior:
Installing MoPub's libraries via Cocoapods should run without error.

#### Observed behavior:
> [!] Can't merge user_target_xcconfig for pod targets: ["FBAudienceNetwork", "MoPub-FacebookAudienceNetwork-Adapters", "MoPub", "Network", "Core", "NativeAds"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.
>
> [!] Can't merge user_target_xcconfig for pod targets: ["FBAudienceNetwork", "MoPub-FacebookAudienceNetwork-Adapters", "MoPub", "Network", "Core", "NativeAds"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

**Comment by chauduyphanvu** [comment]
@dfabulich, we'll take a look and see what can be done here.

Could you confirm if the above are warning instead of errors (and that they shouldn't block you from compiling the adapters)?

Vu Chau
MoPub Team

**Comment by dfabulich** [comment]
Yes, it appears to be just a warning affect. I'm pretty sure y'all just need to merge PR #345 to fix this.

**Comment by chauduyphanvu** [comment]
This is now resolved in the one of the more recent Facebook AN adapters release. 

Note that you might continue seeing the same warning but for other (non-mediation) pods—those will be taken care of by the rest of the team in upcoming release(s).
