### ISSUE TITLE
Fullscreen test ad has no close button

### ISSUE THREAD

**Issue by jw8** [mopub/mopub-ios-sdk#385]
My fullscreen ad (using a test ad unit id) does not show a close button, so there's no way to close the ad.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
I've integrated the SDK via CocoaPods, like this: 
`pod 'mopub-ios-sdk'`
...so I guess that would be the _latest_ SDK version?

#### Device model and OS Version:
Device model: iPhone 11
OS Version: iOS 14.4

#### Xcode Version:
12.4

#### Ad Unit IDs used in reproducing the issue:
"4f117153f5c24fa6a3a92b818a5eb630" (this is a test ad unit found here: https://developers.mopub.com/publishers/ios/test/)

#### Steps to reproduce the behavior:
1) Integrate the MoPub SDK into a Swift iOS app via CocoaPods.
2) Code a fullscreen ad implementation using the aforementioned test ad unit id.
3) Show the ad.
4) Observe the lack of a close button.

#### Expected behavior:
The ad should have a close button overlaid above the ad content.

#### Observed behavior:
The ad does not have a close button.

#### Evidence:
![IMG_0052](https://user-images.githubusercontent.com/12386324/116998042-7e5a9380-ac92-11eb-9a1a-a559798f744e.PNG)

**Comment by dravyan** [comment]
@jw8, thank you for the report. We are not able to reproduce the issue on our end. Could you check if you can replicate the issue using the [MoPub sample app](https://github.com/mopub/mopub-ios-sdk/tree/master/Canary)?

Thanks,
MoPub Team

**Comment by jw8** [comment]
@dravyan Thank you for the reply. I will see what I can do with the MoPub sample app, but is there any information you can give me about this problem? Do you have any idea what _might_ be causing it?

The test ad shows up as expected, and the test is successful when I tap on the ad -- there's just no close button. If the problem were my own implementation, I would expect the ad not to load at all.

Please advise.

Thanks!

**Comment by jw8** [comment]
As it turns out, the problem was my own implementation. I was using `MPAdView` instead of `MPInterstitialAdController`.

Problem solved.

Thank you.
