### ISSUE TITLE
App crashes at startup after adding MoPubSDK 5.16.2

### ISSUE THREAD

**Issue by Ultima2876** [mopub/mopub-ios-sdk#386]
App crash on iOS 10 after adding MoPubSDK 5.16.2 (iOS 10.3.4)

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.16.2

#### Device model and OS Version:
iPhone SE, iOS 10.3.4

#### Xcode Version:
12.5

#### Ad Unit IDs used in reproducing the issue:
N/A

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

1) Build app with MoPubSDK.xcframework, 5.16.2
2) Deploy app on device
3) App crashes on startup with error: `dyld: Library not loaded: @rpath/libswiftCore.dylib`

#### Expected behavior:
As concisely as possible, describe the expected behavior.

App starts cleanly without crash on iOS 10.3.4.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

App crashes on startup with missing swift dylib on iOS 10. It works perfectly on iOS 11+, or if "Always Embed Swift Standard Libraries" is checked, but this added 70mb to app filesize.

Error: `dyld: Library not loaded: @rpath/libswiftCore.dylib`

Potential solution would be to remove reliance on swift core library, or change reliance based on whether app is running on iOS 11+.

#### Evidence:
Device log files, Network log file, etc.
![IMG_0473a](https://user-images.githubusercontent.com/285405/117080719-5290e980-ad36-11eb-8359-5f4d554ea9ff.PNG)

**Comment by dravyan** [comment]
@Ultima2876, thank you for the report. We will take a look and get back.

-MoPub Team

**Comment by dravyan** [comment]
@Ultima2876, That is expected. MoPub SDK contains Swift code and hence you will need to enable "Always Embed Swift Standard Libraries". This will increase the binary size supporting older versions of iOS (< 12.4) if the codebase doesn’t already contain Swift code.

**Comment by Ultima2876** [comment]
Thanks for your response. Should you perhaps document this somewhere?

**Comment by chenxi141017** [comment]
Same crash on iPhoneX iOS 12.1.4.
Please document on https://developers.mopub.com/publishers/ios/integrate/

**Comment by dravyan** [comment]
Documentation is updated https://developers.mopub.com/publishers/ios/integrate/#option-1-integrate-the-sdk-using-cocoapods. Thank you!
