### ISSUE TITLE
MPAdContainerView is not centred in MPAdView when a MRAID banner is displayed.

### ISSUE THREAD

**Issue by sgabello** [mopub/mopub-ios-sdk#387]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Load a 320x50 MRAID banner when the frame of MPAdView is larger.

#### Expected behavior:
`MPAdContainerView` should be centred in the containing `MPAdView`.

#### Observed behavior:
MRAID banners are not centred in the `MPAdView` view. Ref: https://github.com/mopub/mopub-ios-sdk/blob/3e1382ed6686c59cf83d259f2bd8796de6c88c55/MoPubSDK/MPAdView.m#L90

#### Evidence:
Check UIView debug hierarchy attached.
<img width="1440" alt="Screenshot 2021-05-05 at 12 46 05" src="https://user-images.githubusercontent.com/3297/117208132-641bd500-adba-11eb-8518-e97ff74dba30.png">

**Comment by chauduyphanvu** [comment]
@sgabello, thanks for the report! We'll investigate this and get back to you with any updates. Stay tuned!

**Comment by chauduyphanvu** [comment]
@sgabello, while we don't have an update for this yet, we have changes planned for the future to address it. We'll be in touch when the change is in production.

**Comment by sgabello** [comment]
@chauduyphanvu thanks for the update. I've implemented my own fix for now. Looking forward for the official one.

**Comment by SimpsOff** [comment]
I'm waiting for an official fix for this still.

**Comment by ddaddy** [comment]
I'm just implementing MoPub for the first time, and when I request a banner ad using the MoPub Test Unit `0ac59b0996d947309c33f59d6676399f` it appears centred i the `MPAdView`, however when I request an ad using my own accounts ad unit id it is formatted to the left and not centred.
Any idea how to correct this?

**Comment by chauduyphanvu** [comment]
@ddaddy, you can use the `adViewDidLoadAd` callback to get the ad's actual size to resize your container.

Example in our sample app: https://github.com/mopub/mopub-ios-sdk/blob/master/Canary/Canary/Formats/BannerAdDataSource.swift#L177-L188

**Comment by ddaddy** [comment]
I actually looked at that and even implemented the method, but for some reason didn't see the `adSize` param and looked at the `view.frame` instead 🙄

Thank you.
