### ISSUE TITLE
Not able to compile in IOS

### ISSUE THREAD

**Issue by Charlinjoeaht** [mopub/mopub-ios-sdk#390]
The mopub-ios-sdk version 5.17.0 is throwing the following error in IOS

 Command CompileSwift failed with a nonzero exit code
    /ios/Pods/mopub-ios-sdk/MoPubSDK/Internal/Utility/Categories/SKAdImpression+ConvenienceServerResponseInitializer.swift:12:11: error: cannot find type
    'SKAdImpression' in scope
    extension SKAdImpression {
              ^~~~~~~~~~~~~~
    /ios/Pods/mopub-ios-sdk/MoPubSDK/Internal/Common/SKAdNetworkData.swift:113:38: error: cannot find type 'SKAdImpression' in scope
        @objc public var impressionData: SKAdImpression? {
                                         ^~~~~~~~~~~~~~
    /ios/Pods/mopub-ios-sdk/MoPubSDK/Internal/Common/SKAdNetworkData.swift:88:42: error: cannot find 'SKAdImpression' in scope
                localImpressionDataStorage = SKAdImpression(serverResponse: impressionResponseDictionary) ?? nil

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@Charlinjoeaht, please ensure you are using Xcode 12.5 according to the new requirements: https://github.com/mopub/mopub-ios-sdk#new-in-this-version.

Vu Chau
MoPub Team
