### ISSUE TITLE
NSInvalidArgumentException in OMIDMopubJSNetworkBridge handleInjectJavaScript

### ISSUE THREAD

**Issue by ashwingv93** [mopub/mopub-ios-sdk#392]
App is crashing with NSInvalidArgumentException from MoPub in certain scenario.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
We are not able to reproduce the issue in development. But we are seeing it in production.
So we do not know the exact steps to reproduce.

#### Expected behavior:
App should not crash

#### Observed behavior:
App crashes during Ad request

#### Evidence:
**Crash log**

NSInvalidArgumentException: *** -[__NSCFString stringByAppendingString:]: nil argument

0  CoreFoundation          ___exceptionPreprocess
1  libobjc.A.dylib         _objc_exception_throw
2  Foundation              -[NSString stringByAppendingString:]
3  MoPubSDK                -[OMIDMopubJSNetworkBridge handleInjectJavaScript:injectionID:orError:]
4  MoPubSDK                __64-[OMIDMopubJSNetworkBridge injectJavaScriptFromURL:injectionID:]_block_invoke
5  MoPubSDK                __50-[OMIDMopubLoadTask handleResponseWithData:error:]_block_invoke
6  libdispatch.dylib       __dispatch_call_block_and_release
7  libdispatch.dylib       __dispatch_client_callout
8  libdispatch.dylib       __dispatch_lane_serial_drain
9  libdispatch.dylib       __dispatch_lane_invoke
10 libdispatch.dylib       __dispatch_workloop_worker_thread
11 libsystem_pthread.dylib __pthread_wqthread
12 libsystem_pthread.dylib _start_wqthread

**Comment by chauduyphanvu** [comment]
@ashwingv93, thanks for letting us know! I've let the rest of the team know and we'll see what can be done here. Stay tuned!

Vu Chau
MoPub Team

**Comment by wacamoe** [comment]
Hi @ashwingv93 - as this is code inside of a library we do not own, there isn't a whole lot we can do. I have, however, contacted the IAB with the bug report and will update as we get some more information from them. Thanks for hanging with us here.

-Kyle

**Comment by ashwingv93** [comment]
@wacamoe We had seen this error previously as well around 5 per week. Only since last week, number of such errors have increased drastically to 500 per day and nothing changed from code side.
Can you tell us what causes this issue? Can anything be changed in MoPub or other ad network configuration to reduce these errors?

**Comment by xiayun1990** [comment]
@ashwingv93  me too

**Comment by chauduyphanvu** [comment]
@ashwingv93, this issue is caused by server-side scripts used for [viewability](https://developers.mopub.com/publishers/android/viewability/) in certain ads. The IAB is in the process of patching this and the fix will be rolled out server-side, so that crashes like this will no longer occur.

At this time, it looks like you will not need to update the MoPub SDK to get the fix. If that changes, we'll post an update here.

**Comment by ashwingv93** [comment]
@chauduyphanvu This error has spiked since last 5 hours. We are seeing around 100 crashes per hour due to this error.
Can you inform IAB to expedite the fix? This crash is affecting our app health in iOS.

**Comment by chauduyphanvu** [comment]
@ashwingv93, thanks for the information! We will let the IAB know of the urgency on your behalf.

As an update, a new MoPub SDK will be needed to incorporate the IAB fix once it is available to us. You will likely need to update to that MoPub SDK version. Stay tuned for more updates.

**Comment by ashwingv93** [comment]
@chauduyphanvu, is there any update on this issue?
Number of crashes due to this error has reduced since July 11th.

**Comment by chauduyphanvu** [comment]
@ashwingv93, thanks for letting us know the crash rate has decreased! There aren't any updates that we are aware of. We'll let you know when there is one.
