### ISSUE TITLE
Unable to build application with mopub-ios-sdk on Xcode 12.5.1 on MacBook with M1 chip

### ISSUE THREAD

**Issue by Freisluker** [mopub/mopub-ios-sdk#395]
One line summary of the issue here

- [+] I am submitting a bug report for existing functionality
- [+] I visited https://developers.mopub.com/ and found no answer
- [+] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [+] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.17.0

#### Device model and OS Version:
Apple MacBook Pro 13 2020 M1
iOS 12 Pro Simulator, iOS 14.5 (18E182) 

#### Xcode Version:
Xcode version 12.5.1 (12E507)

#### Ad Unit IDs used in reproducing the issue:
-

#### Steps to reproduce the behavior:
Install mopub iOS sdk via Cocoapods.
Integrate framework to the project via Tuist
Try to build application

#### Expected behavior:
Application built successfully

#### Observed behavior:
Swift Compiler Error with log .../CommonModules/Banners/Sources/Service/BannerService.swift:10:8: Module 'MoPubSDK' was created for incompatible target arm64-apple-ios10.0: .../Pods/_Prebuild/GeneratedFrameworks/mopub-ios-sdk/MoPubSDK.framework/Modules/MoPubSDK.swiftmodule/arm64.swiftmodule

#### Additional comment:

It's impossible to integrate mopub-sdk-ios via Carthage or SPM (one of solutions with Apple Silicon Macs is to use xcframework) so I can't build framework other way. Can you please update .podspec to build xcframework or add support of Carthage or SPM, so library will work on last Xcode and Mac with M1 chip.

It's not only framework in the project, so I can not exclude arm64 architecture in project build settings

**Comment by chauduyphanvu** [comment]
@Freisluker, thanks for the report. I've relayed this to the rest of the team and will circle back with an update.

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
@Freisluker, we can confirm that the MoPub iOS SDK compiles just fine on M1. This is likely an issue with Tuist/Carthage/SPM. I'd recommend checking with those platforms on a possible resolution for this issue.

Let us know if you have any other questions!

**Comment by Freisluker** [comment]
Thanks, @chauduyphanvu ,

In general we can not integrate mopub sdk with Carthage/SPM because there is no support in your sdk. I will try to create simple project and integrate mopub sdk there. Do you use Rosetta mode in Xcode? in general i can build mopub sdk via Cocoapods, but i can not run project with it because of issue i reported. Anyway, thanks for your help, i will add more information if i find something

**Comment by chauduyphanvu** [comment]
@Freisluker, thank you for the confirmation that you can build the MoPub SDK via CocoaPods. As I said earlier we won't be able to comment on any third-party frameworks that assist in the integration process. Have you raised the issue to their developers? 

> but i can not run project with it because of issue i reported

What are those issues? Are you referring to the below?

```
Swift Compiler Error with log .../CommonModules/Banners/Sources/Service/BannerService.swift:10:8: Module 'MoPubSDK' was created for incompatible target arm64-apple-ios10.0: .../Pods/_Prebuild/GeneratedFrameworks/mopub-ios-sdk/MoPubSDK.framework/Modules/MoPubSDK.swiftmodule/arm64.swiftmodule
```

**Comment by Freisluker** [comment]
Hi, @chauduyphanvu, thanks for answer.

We did't raise any issues to integration services developers , for now i'm in progress of creating test project with same integration stuff, i just want to show you, that ".framework" type is too old for Apple Silicon M1 acrhitectures and it's impossible to build xcframework without changes in your project (.podspec file should contain such information). We don't have any issues with other libraries which are integrated with Carthage, SPM or Cocoapods. 

And yes, you're right about issue - so for now i think we can try to integrate your sdk as subproject (not via Cocoapods), but in future it will be really good if we can build XCFramework via Cocoapods (you can check OMSDK - baceuse after building with cocoapods it creates XCFramework).

I will provide you a link to the repository with test project when i finish.
