### ISSUE TITLE
React-Native Plugin

### ISSUE THREAD

**Issue by senolatac** [mopub/mopub-ios-sdk#398]
How can I implement it on react-native? Do you have any suggestion to use mopub on react-native?

- [ ] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@senolatac, thanks for your inquiry. We do not support React Native integrations at this time. If that changes, we will post an update and let you know!

Vu Chau
MoPub Team
