### ISSUE TITLE
Getting crash as and when app starts running after build successfull.

### ISSUE THREAD

**Issue by jeetb441** [mopub/mopub-ios-sdk#399]
- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked to make sure that this issue has not already been filed

#### Expected behavior:
App should go as per flow set through splash screen.

#### Observed behavior:
As an and app build is successful app is getting crashed. Tried removing pod and manually adding SDK into project, but problem was not solved. One of my friends' has macbook pro M1, tested the project into his system, it's working fine.

#### Evidence:
Device log files, Network log file, etc.
<img width="1440" alt="Screenshot 2021-08-06 at 7 18 29 PM" src="https://user-images.githubusercontent.com/34486897/128520624-a88fb6b9-8523-4371-981e-500c818e9f47.png">

**Comment by dravyan** [comment]
@jeetb441, thank you for the report. v5.12.1 does not support M1. Try updating to at least [v5.17.0](https://github.com/mopub/mopub-ios-sdk/releases) that supports iOS Simulators on Apple Silicon Macs.

Thanks,
MoPub Team
