### ISSUE TITLE
Crash in MPImageLoader

### ISSUE THREAD

**Issue by seanLee** [mopub/mopub-ios-sdk#402]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil

#### Observed behavior:
Crash log of Firebase with 

#### Evidence:
0 CoreFoundation  __exceptionPreprocess
1 libobjc.A.dylib objc_exception_throw
2 CoreFoundation -[__NSCFString characterAtIndex:].cold.1
3 CoreFoundation -[__NSArrayM insertObject:atIndex:].cold.2
4 CoreFoundation -[__NSArrayM insertObject:atIndex:]
5 UIKitCore -[UIImageView _setImageViewContentsForAnimatedImage:]
6 UIKitCore -[UIImageView _setImageViewContents:]
7 UIKitCore -[UIImageView _updateState]
8 UIKitCore +[UIView(Animation) performWithoutAnimation:]
9 UIKitCore -[UIImageView _updateImageViewForOldImage:newImage:]
10 UIKitCore -[UIImageView setImage:]
11 XXXXXXX MPImageLoader.m -  Line 104 
 __53-[MPImageLoader safeMainQueueSetImage:intoImageView:]_block_invoke + 104

**Comment by dravyan** [comment]
@seanLee, thanks for the report. Could you share the steps to replicate the issue on our end?

Thanks,
MoPub Team

**Comment by seanLee** [comment]
I'am sorry that we can not replicate the crash in simulator.Our usage of mopub SDK is to mediate the third-party ad,after adding Facebook & Admob ad to the ad-unit,we get this crash.I have searched this issue in both Google and StackOverflow,found little documents about this.According to the crash stack,it seems that crashed when dealing with GIF image,but which the actual provider is,Facebook or Admob,we can not judge.

**Comment by dravyan** [comment]
@seanLee, could you confirm the ad format here and add some logging to monitor which demand source is the ad from?

**Comment by seanLee** [comment]
It is seems that I found the reason why I will crash after I deep into my code.The ad request return object of ```kAdMainImageKey``` key while I did not set the ```kAdMainImageKey```. However, my code set the ```mainImageView``` a size of CGFLOAT_MIN,and the crash occurred when a animatedImage set to the CGFLOAT_MIN-size UIImageView.
Now there is only one point I wanna to know:
Is there any chance that the response return ```mainImage``` with out the ```kAdMainImageKey``` key?
