### ISSUE TITLE
Issue with Mopub banner when calling trackSKAdNetworkStartImpressionForConfiguration method in MPAnalyticsTracker

### ISSUE THREAD

**Issue by n3ir0** [mopub/mopub-ios-sdk#405]
One line summary of the issue here

- [v] I am submitting a bug report for existing functionality
- [v] I visited https://developers.mopub.com/ and found no answer
- [v] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [v] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.17.0

#### Device model and OS Version:
iPhone XR  iOS 14.5

#### Xcode Version:
12.5

#### Ad Unit IDs used in reproducing the issue:
I've attached response for this banner
[ad response.json.zip](https://github.com/mopub/mopub-ios-sdk/files/7090663/ad.response.json.zip)

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
Receive Mopub banner. This will trigger trackSKAdNetworkStartImpressionForConfiguration method in MPAnalyticsTracker. And this in turn will trigger that code:

[SKAdNetwork startImpression:storeKitImpression completionHandler:^(NSError * _Nullable error) {
                    if (error == nil) {
                        return;
                    }
                    MPLogError(@"SKAdNetwork startImpression failed with error: %@", error);
 }];

And in a case of iPhone XR  iOS 14.5 the completionHandler will not been executed and this will freeze application. Other models with the same OS work fine, also iPhone XR  iOS 14.5 simulator works fine, problem is on device.

The solution is to send this code to global queue like this:

dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
                [SKAdNetwork startImpression:storeKitImpression completionHandler:^(NSError * _Nullable error) {
                    if (error == nil) {
                        return;
                    }
                    MPLogError(@"SKAdNetwork startImpression failed with error: %@", error);
                }];
});

Is it OK to call "SKAdNetwork startImpression" from global queue?

#### Expected behavior:
Occurrence of Mopub banner does not freeze the application.

#### Observed behavior:
Occurrence of Mopub banner freezes the application due to "SKAdNetwork startImpression" call freeze.

#### Evidence:
Device log files, Network log file, etc.

**Comment by p158276** [comment]
Hi @n3ir0 ,
Thanks for putting all the information here. This seems to be an Apple OS issue that has been solved in [14.5.1 onward](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14_5_1-release-notes). Are you able to see the crash on other OS versions? Besides, is it 100% reproducible on the iOS 14.5 devices? 

Even we tried to dispatch the queue, there would still be a deadlock in the background queue. I'll bring this back to our internal team and provide the update here.

Thanks.

Yoyo Lin
MoPub Team

**Comment by n3ir0** [comment]
This bug is reproducible only on iPhone XR 14.5 (device, not simulator). On other devices with same OS thats ok.

**Comment by p158276** [comment]
Hi @n3ir0 ,
Thanks for all the information here. Please update the device to 14.5.1+ and see if the issue still persists. From the [change log](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14_5_1-release-notes), the issue shouldn't happen after the OS version being upgraded.

Thanks.

**Comment by n3ir0** [comment]
Updated to 14.7.1 - no problem. Yes, it seems that it was fixed in 14.5.1.
