### ISSUE TITLE
keyWindow, statusBarOrientation, statusBarHidden, statusBarFrame deprecated in iOS 13.0

### ISSUE THREAD

**Issue by saldous** [mopub/mopub-ios-sdk#414]
Lots of warnings in Xcode about deprecations in iOS 13.0
![image](https://user-images.githubusercontent.com/3334306/151077847-89956b1e-753c-404f-a37b-56dc9acaf006.png)

**Comment by kylegrymonprez** [comment]
@saldous - Thanks for the issue.

The MoPub platform, including network mediation, Advanced Bidding and Marketplace, will sunset on March 31, 2022. Due to the sale of platform, we will not be releasing an update to the SDK to address this issue.

Thanks for using MoPub!
