### ISSUE TITLE
Status bar disappears after fullscreen iAd banner display

### ISSUE THREAD

**Issue by evilutioner** [mopub/mopub-ios-sdk#96]
This issue is reproduces for the latest Mopub version 3.3.0.

I discovered that dismissInterstitialAnimated in MPInterstitialViewController.h doesn't call for iAd after banner closing.
- (void)dismissInterstitialAnimated:(BOOL)animated
  {
  [self setApplicationStatusBarHidden:!self.applicationHasStatusBar];
  ...
  }

**Comment by orkenstein** [comment]
Same hear
